// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../Node/Fs.res.js";
import * as Mime from "./Mime.res.js";
import * as Path from "../Utils/Path.res.js";
import * as Types from "../Types.res.js";
import * as Logger from "../Utils/Logger.res.js";
import * as Headers from "../Security/Headers.res.js";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Injector from "../Ui/Injector.res.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Node_Path from "../Node/Node_Path.res.js";
import * as Templates from "../Ui/Templates.res.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function respond(status, headers, body, logLevel, logMsg) {
  let withSec = Headers.withSecurityHeaders(headers);
  Logger.log(logLevel, logMsg);
  return {
    TAG: "Respond",
    _0: {
      status: status,
      headers: withSec,
      body: body
    }
  };
}

function getContentLength(headers) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= headers.length) {
      return;
    }
    let match = headers[i];
    if (match !== undefined) {
      if (match[0] === "content-length") {
        let parsed = Belt_Int.fromString(match[1]);
        if (parsed !== undefined && parsed > 0) {
          return parsed;
        } else {
          return;
        }
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function getUpgradeHeader(headers) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= headers.length) {
      return;
    }
    let match = headers[i];
    if (match !== undefined) {
      if (match[0] === "upgrade") {
        return match[1];
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function classifyFsError(error) {
  let msg = error.message;
  if (!(msg == null) && Js_string.includes(msg, "ENOENT")) {
    return 404;
  } else {
    return 500;
  }
}

function serveFile(method, safePath, enableLiveReload, port) {
  let mime = Mime.fromPath(safePath);
  let baseHeaders = [
    [
      "content-type",
      mime.contentType
    ],
    [
      "cache-control",
      "no-cache"
    ]
  ];
  if (method === "HEAD") {
    return Promise.resolve({
      TAG: "Respond",
      _0: {
        status: 200,
        headers: Headers.withSecurityHeaders(baseHeaders),
        body: "Empty"
      }
    });
  }
  if (enableLiveReload && mime.contentType === "text/html") {
    return Stdlib_Promise.$$catch(Fs.readTextFile(safePath).then(html => {
      let injected = Injector.injectLiveReloadScript(html, port);
      return Promise.resolve({
        TAG: "Respond",
        _0: {
          status: 200,
          headers: Headers.withSecurityHeaders(baseHeaders),
          body: {
            TAG: "Html",
            _0: injected
          }
        }
      });
    }), _error => Promise.resolve({
      TAG: "Respond",
      _0: {
        status: 500,
        headers: Headers.withSecurityHeaders([[
            "content-type",
            "text/plain; charset=utf-8"
          ]]),
        body: "Empty"
      }
    }));
  }
  let finalHeaders;
  if (mime.contentType === "image/svg+xml") {
    let basename = Node_Path.basename(safePath);
    let noQuotes = Js_string.replaceByRe(/\"/g, basename, "");
    finalHeaders = baseHeaders.concat([[
        "content-disposition",
        "attachment; filename=\"" + noQuotes + "\""
      ]]);
  } else {
    finalHeaders = baseHeaders;
  }
  return Promise.resolve({
    TAG: "Respond",
    _0: {
      status: 200,
      headers: Headers.withSecurityHeaders(finalHeaders),
      body: {
        TAG: "File",
        _0: safePath
      }
    }
  });
}

function handle(config, request) {
  let match = getContentLength(request.headers);
  if (match !== undefined) {
    return Promise.resolve(respond(413, [[
        "content-type",
        "text/plain; charset=utf-8"
      ]], "Empty", "Error", "413 Payload Too Large: " + request.path));
  }
  let upperMethod = request.method.toUpperCase();
  if (upperMethod !== "GET" && upperMethod !== "HEAD") {
    return Promise.resolve(respond(405, [
      [
        "content-type",
        "text/plain; charset=utf-8"
      ],
      [
        "allow",
        "GET, HEAD"
      ]
    ], "Empty", "Info", "405 Method Not Allowed: " + upperMethod + " " + request.path));
  }
  let decodedOr400;
  try {
    decodedOr400 = {
      TAG: "Ok",
      _0: decodeURIComponent(request.path)
    };
  } catch (exn) {
    decodedOr400 = {
      TAG: "Error",
      _0: respond(400, [[
          "content-type",
          "text/plain; charset=utf-8"
        ]], "Empty", "Error", "400 Bad Request: " + request.path)
    };
  }
  if (decodedOr400.TAG !== "Ok") {
    return Promise.resolve(decodedOr400._0);
  }
  let decodedPath = decodedOr400._0;
  if (config.enableLiveReload && decodedPath === Types.liveReloadEndpoint && Primitive_object.equal(getUpgradeHeader(request.headers), "websocket")) {
    return Promise.resolve("WsUpgrade");
  }
  let safePath = Path.resolveSafePath(config.directory, decodedPath);
  if (safePath !== undefined) {
    let relPath = Node_Path.relative(config.directory, safePath);
    let normalized = relPath.replace(/\\/g, "/");
    if (Path.matchesPattern(normalized, config.ignorePatterns)) {
      Logger.log("Debug", "403 Forbidden: ignored path " + request.path);
      return Promise.resolve(respond(403, [[
          "content-type",
          "text/plain; charset=utf-8"
        ]], "Empty", "Debug", "403 Forbidden (ignored): " + request.path));
    } else {
      return Stdlib_Promise.$$catch(Path.hasSymlinkPrefix(config.directory, safePath).then(hasSymlink => {
        if (hasSymlink) {
          Logger.log("Error", "403 Forbidden: symlink in path " + request.path);
          return Promise.resolve(respond(403, [[
              "content-type",
              "text/plain; charset=utf-8"
            ]], "Empty", "Error", "403 Forbidden (symlink): " + request.path));
        } else {
          return Stdlib_Promise.$$catch(Fs.lstat(safePath).then(lstatInfo => {
            if (lstatInfo.isSymlink) {
              Logger.log("Error", "403 Forbidden: symlink target " + request.path);
              return Promise.resolve(respond(403, [[
                  "content-type",
                  "text/plain; charset=utf-8"
                ]], "Empty", "Error", "403 Forbidden (symlink target): " + request.path));
            } else {
              return Stdlib_Promise.$$catch(Fs.stat(safePath).then(statInfo => {
                if (statInfo.isFile) {
                  return serveFile(upperMethod, safePath, config.enableLiveReload, config.port);
                }
                if (!statInfo.isDirectory) {
                  return Promise.resolve(respond(404, [[
                      "content-type",
                      "text/plain; charset=utf-8"
                    ]], "Empty", "Error", "404 Not Found: " + request.path));
                }
                if (config.enableDirectoryListing) {
                  let enableLiveReload = config.enableLiveReload;
                  let port = config.port;
                  let ignorePatterns = config.ignorePatterns;
                  if (upperMethod === "HEAD") {
                    return Promise.resolve({
                      TAG: "Respond",
                      _0: {
                        status: 200,
                        headers: Headers.withSecurityHeaders([[
                            "content-type",
                            "text/html; charset=utf-8"
                          ]]),
                        body: "Empty"
                      }
                    });
                  } else {
                    return Stdlib_Promise.$$catch(Fs.readdir(safePath).then(entries => {
                      let filtered = entries.filter(entry => {
                        let relPath = entry.name;
                        let normalized = relPath.replace(/\\/g, "/");
                        return !Path.matchesPattern(normalized, ignorePatterns);
                      });
                      let fileEntries = filtered.map(entry => {
                        let entryUrl = decodedPath === "/" ? "/" + encodeURIComponent(entry.name) : decodedPath + "/" + encodeURIComponent(entry.name);
                        return {
                          name: entry.name,
                          isDirectory: entry.isDirectory,
                          url: entryUrl
                        };
                      });
                      let arr = fileEntries.slice();
                      arr.sort((a, b) => {
                        if (a.isDirectory && !b.isDirectory) {
                          return -1.0;
                        }
                        if (!a.isDirectory && b.isDirectory) {
                          return 1.0;
                        }
                        let cmp = a.name.localeCompare(b.name);
                        if (cmp < 0.0) {
                          return -1.0;
                        } else if (cmp > 0.0) {
                          return 1.0;
                        } else {
                          return 0.0;
                        }
                      });
                      let capped = arr.slice(0, 100);
                      let truncatedCount = arr.length - capped.length | 0;
                      let html = Templates.renderDirectoryListing(capped, decodedPath);
                      let finalHtml = truncatedCount > 0 ? html.replace("</main>", "<div class=\"empty-state\">Directory listing truncated after 100 entries (" + String(truncatedCount) + " more not shown)</div></main>") : html;
                      let withInjection = enableLiveReload ? Injector.injectLiveReloadScript(finalHtml, port) : finalHtml;
                      return Promise.resolve({
                        TAG: "Respond",
                        _0: {
                          status: 200,
                          headers: Headers.withSecurityHeaders([[
                              "content-type",
                              "text/html; charset=utf-8"
                            ]]),
                          body: {
                            TAG: "Html",
                            _0: withInjection
                          }
                        }
                      });
                    }), _error => Promise.resolve({
                      TAG: "Respond",
                      _0: {
                        status: 500,
                        headers: Headers.withSecurityHeaders([[
                            "content-type",
                            "text/plain; charset=utf-8"
                          ]]),
                        body: "Empty"
                      }
                    }));
                  }
                }
                let indexPath = Node_Path.join(safePath, "index.html");
                return Stdlib_Promise.$$catch(Fs.lstat(indexPath).then(indexInfo => {
                  if (indexInfo.isSymlink) {
                    Logger.log("Error", "403 Forbidden: index.html is symlink " + request.path);
                    return Promise.resolve(respond(403, [[
                        "content-type",
                        "text/plain; charset=utf-8"
                      ]], "Empty", "Error", "403 Forbidden (index symlink): " + request.path));
                  } else {
                    return Stdlib_Promise.$$catch(Fs.stat(indexPath).then(param => serveFile(upperMethod, indexPath, config.enableLiveReload, config.port)), param => {
                      Logger.log("Debug", "403 Directory listing disabled: " + request.path);
                      return Promise.resolve(respond(403, [[
                          "content-type",
                          "text/plain; charset=utf-8"
                        ]], "Empty", "Debug", "403 Directory listing disabled: " + request.path));
                    });
                  }
                }), param => {
                  Logger.log("Debug", "403 Directory listing disabled: " + request.path);
                  return Promise.resolve(respond(403, [[
                      "content-type",
                      "text/plain; charset=utf-8"
                    ]], "Empty", "Debug", "403 Directory listing disabled: " + request.path));
                });
              }), fsError => {
                let code = classifyFsError(fsError);
                if (code === 404) {
                  Logger.log("Error", "404 Not Found: " + request.path);
                } else {
                  Logger.log("Error", "500 Internal Server Error: " + Stdlib_Nullable.getWithDefault(fsError.message, "Unknown error"));
                }
                return Promise.resolve(respond(code, [[
                    "content-type",
                    "text/plain; charset=utf-8"
                  ]], "Empty", "Error", code === 404 ? "404 Not Found: " + request.path : "500 Internal Server Error: " + request.path));
              });
            }
          }), fsError => {
            let code = classifyFsError(fsError);
            if (code === 404) {
              Logger.log("Error", "404 Not Found: " + request.path);
            } else {
              Logger.log("Error", "500 Internal Server Error: " + Stdlib_Nullable.getWithDefault(fsError.message, "Unknown error"));
            }
            return Promise.resolve(respond(code, [[
                "content-type",
                "text/plain; charset=utf-8"
              ]], "Empty", "Error", code === 404 ? "404 Not Found: " + request.path : "500 Internal Server Error: " + request.path));
          });
        }
      }), _fsError => {
        Logger.log("Error", "500 Internal Server Error: symlink check failed " + request.path);
        return Promise.resolve(respond(500, [[
            "content-type",
            "text/plain; charset=utf-8"
          ]], "Empty", "Error", "500 Internal Server Error: " + request.path));
      });
    }
  }
  Logger.log("Error", "403 Forbidden: path traversal blocked " + request.path);
  return Promise.resolve(respond(403, [[
      "content-type",
      "text/plain; charset=utf-8"
    ]], "Empty", "Error", "403 Forbidden: " + request.path));
}

function make(config) {
  return req => handle(config, req);
}

export {
  make,
  handle,
}
/* Fs Not a pure module */
