// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node_Path from "../Node/Node_Path.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let mimeTable = [
  [
    "html",
    "text/html",
    true
  ],
  [
    "htm",
    "text/html",
    true
  ],
  [
    "css",
    "text/css",
    true
  ],
  [
    "js",
    "text/javascript",
    true
  ],
  [
    "mjs",
    "text/javascript",
    true
  ],
  [
    "json",
    "application/json",
    false
  ],
  [
    "txt",
    "text/plain",
    true
  ],
  [
    "svg",
    "image/svg+xml",
    false
  ],
  [
    "png",
    "image/png",
    false
  ],
  [
    "jpg",
    "image/jpeg",
    false
  ],
  [
    "jpeg",
    "image/jpeg",
    false
  ],
  [
    "gif",
    "image/gif",
    false
  ],
  [
    "webp",
    "image/webp",
    false
  ],
  [
    "ico",
    "image/x-icon",
    false
  ],
  [
    "wasm",
    "application/wasm",
    false
  ],
  [
    "map",
    "application/json",
    false
  ]
];

function lookupExt(ext) {
  let lower = ext.toLowerCase();
  return Stdlib_Option.map(mimeTable.find(entry => entry[0] === lower), entry => ({
    contentType: entry[1],
    isText: entry[2]
  }));
}

function mimeFor(ext) {
  let m = lookupExt(ext);
  if (m !== undefined) {
    return m;
  } else {
    return {
      contentType: "application/octet-stream",
      isText: false
    };
  }
}

function fromPath(path) {
  let raw = Node_Path.extname(path);
  let c = raw[0];
  return mimeFor(c === "." ? raw.slice(1, raw.length) : raw);
}

export {
  mimeFor,
  fromPath,
}
/* Node_Path Not a pure module */
