// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "../Node/Process.res.js";

let default_directory = Process.cwd();

let default_ignorePatterns = [
  ".git",
  "node_modules",
  ".DS_Store"
];

let $$default = {
  directory: default_directory,
  hostname: "127.0.0.1",
  port: 8080,
  ignorePatterns: default_ignorePatterns,
  enableDirectoryListing: false,
  logLevel: "Info",
  enableLiveReload: true,
  restartOnChange: false,
  lan: false,
  allowProtectedDir: false
};

export {
  $$default as default,
}
/* default Not a pure module */
