// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "../Types.res.js";

function liveReloadScript(port) {
  let scriptContent = "(() => { const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'; const clientPort = window.location.port || '" + port.toString() + "'; const wsUrl = protocol + '//' + window.location.hostname + ':' + clientPort + '" + Types.liveReloadEndpoint + "'; const connect = () => { const ws = new WebSocket(wsUrl); ws.onopen = () => console.log('[Live Reload] Connected'); ws.onmessage = (event) => { if (event.data === '" + Types.liveReloadMessage + "') { console.log('[Live Reload] Reloading page...'); window.location.reload(); } }; ws.onclose = () => { console.log('[Live Reload] Connection closed, attempting to reconnect...'); setTimeout(connect, 1000); }; ws.onerror = () => { console.log('[Live Reload] Connection error, attempting to reconnect...'); setTimeout(connect, 1000); }; }; connect(); })();";
  return "<script>\n" + scriptContent + "\n</script>";
}

function injectLiveReloadScript(html, port) {
  let script = liveReloadScript(port);
  if (html.includes("</body>")) {
    return html.replace("</body>", script + "\n</body>");
  } else if (html.includes("</html>")) {
    return html.replace("</html>", script + "\n</html>");
  } else {
    return html + "\n" + script;
  }
}

export {
  liveReloadScript,
  injectLiveReloadScript,
}
/* No side effect */
