// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(e) {
  if (typeof e !== "object") {
    return "Help requested";
  }
  switch (e.TAG) {
    case "UnknownFlag" :
      return `Unknown flag: ` + e._0;
    case "MissingValue" :
      return `Missing value for flag: ` + e._0;
    case "InvalidPort" :
      return `Invalid port: ` + String(e._0) + `. Must be between 0 and 65535.`;
    case "InvalidLogLevel" :
      return `Invalid log level: ` + e._0 + `. Must be one of: info, debug, error.`;
    case "RemovedFlag" :
      return `Flag has been removed: ` + e._0;
    case "InvalidPath" :
      return `Invalid path: ` + e._0;
  }
}

export {
  toString,
}
/* No side effect */
