// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "../Node/Process.res.js";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Nodepath from "node:path";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parse(args) {
  let directory;
  let hostname;
  let port;
  let ignorePatterns;
  let listing = false;
  let noListing = false;
  let noLiveReload = false;
  let restartOnChange = false;
  let logLevel;
  let lan = false;
  let allowProtectedDir = false;
  let helpRequested = false;
  let parseError;
  let i = 0;
  let argsLen = args.length;
  while (i < argsLen && parseError === undefined) {
    let arg = Stdlib_Option.getOr(args[i], "");
    if (arg === "--help" || arg === "-h") {
      helpRequested = true;
      i = i + 1 | 0;
    } else if (arg === "--dir" || arg === "-d") {
      if ((i + 1 | 0) >= argsLen) {
        parseError = {
          TAG: "MissingValue",
          _0: arg
        };
      } else {
        directory = Stdlib_Option.getOr(args[i + 1 | 0], "");
        i = i + 2 | 0;
      }
    } else if (arg === "--host") {
      if ((i + 1 | 0) >= argsLen) {
        parseError = {
          TAG: "MissingValue",
          _0: arg
        };
      } else {
        hostname = Stdlib_Option.getOr(args[i + 1 | 0], "");
        i = i + 2 | 0;
      }
    } else if (arg === "--port" || arg === "-p") {
      if ((i + 1 | 0) >= argsLen) {
        parseError = {
          TAG: "MissingValue",
          _0: arg
        };
      } else {
        let portStr = Stdlib_Option.getOr(args[i + 1 | 0], "");
        let portNum = Belt_Int.fromString(portStr);
        if (portNum !== undefined) {
          port = portNum;
        } else {
          parseError = {
            TAG: "InvalidPort",
            _0: 0
          };
        }
        i = i + 2 | 0;
      }
    } else if (arg === "--ignore" || arg === "-i") {
      if ((i + 1 | 0) >= argsLen) {
        parseError = {
          TAG: "MissingValue",
          _0: arg
        };
      } else {
        let patternStr = Stdlib_Option.getOr(args[i + 1 | 0], "");
        let patterns = Js_string.split(",", patternStr).map(prim => prim.trim());
        ignorePatterns = patterns;
        i = i + 2 | 0;
      }
    } else if (arg === "--listing") {
      listing = true;
      i = i + 1 | 0;
    } else if (arg === "--no-listing") {
      noListing = true;
      i = i + 1 | 0;
    } else if (arg === "--no-live-reload") {
      noLiveReload = true;
      i = i + 1 | 0;
    } else if (arg === "--restart-on-change" || arg === "-r") {
      restartOnChange = true;
      i = i + 1 | 0;
    } else if (arg === "--log") {
      if ((i + 1 | 0) >= argsLen) {
        parseError = {
          TAG: "MissingValue",
          _0: arg
        };
      } else {
        let levelStr = Stdlib_Option.getOr(args[i + 1 | 0], "");
        switch (levelStr) {
          case "debug" :
            logLevel = "Debug";
            break;
          case "error" :
            logLevel = "Error";
            break;
          case "info" :
            logLevel = "Info";
            break;
          default:
            parseError = {
              TAG: "InvalidLogLevel",
              _0: levelStr
            };
        }
        i = i + 2 | 0;
      }
    } else if (arg === "--lan" || arg === "-l") {
      lan = true;
      i = i + 1 | 0;
    } else if (arg === "--allow-protected-dir") {
      allowProtectedDir = true;
      i = i + 1 | 0;
    } else if (arg === "--rate-limit-max-requests") {
      parseError = {
        TAG: "RemovedFlag",
        _0: "--rate-limit-max-requests"
      };
    } else if (arg === "--rate-limit-window-ms") {
      parseError = {
        TAG: "RemovedFlag",
        _0: "--rate-limit-window-ms"
      };
    } else if (arg === "--trust-proxy") {
      parseError = {
        TAG: "RemovedFlag",
        _0: "--trust-proxy"
      };
    } else if (arg.length > 0 && arg[0] === "-") {
      parseError = {
        TAG: "UnknownFlag",
        _0: arg
      };
    } else {
      i = i + 1 | 0;
    }
  };
  let e = parseError;
  if (e !== undefined) {
    return {
      TAG: "Error",
      _0: e
    };
  }
  if (helpRequested) {
    return {
      TAG: "Error",
      _0: "HelpRequested"
    };
  }
  let d = directory;
  let effectiveDir = d !== undefined ? Nodepath.resolve(d) : Process.cwd();
  let h = hostname;
  let effectiveHost = h !== undefined ? h : (
      lan ? "0.0.0.0" : "127.0.0.1"
    );
  let p = port;
  let effectivePort = p !== undefined ? p : 8080;
  if (effectivePort < 0 || effectivePort > 65535) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPort",
        _0: effectivePort
      }
    };
  }
  let patterns$1 = ignorePatterns;
  let effectiveIgnorePatterns = patterns$1 !== undefined ? patterns$1 : [
      ".git",
      "node_modules",
      ".DS_Store"
    ];
  let effectiveListing = listing && !noListing;
  let l = logLevel;
  let effectiveLogLevel = l !== undefined ? l : "Info";
  let effectiveLiveReload = !noLiveReload;
  return {
    TAG: "Ok",
    _0: {
      directory: effectiveDir,
      hostname: effectiveHost,
      port: effectivePort,
      ignorePatterns: effectiveIgnorePatterns,
      enableDirectoryListing: effectiveListing,
      logLevel: effectiveLogLevel,
      enableLiveReload: effectiveLiveReload,
      restartOnChange: restartOnChange,
      lan: lan,
      allowProtectedDir: allowProtectedDir
    }
  };
}

export {
  parse,
}
/* Process Not a pure module */
