// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Crypto from "../Node/Crypto.res.js";

function computeAccept(clientKey) {
  return Crypto.sha1Base64(clientKey + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11");
}

function handshakeResponse(accept) {
  return "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: " + accept + "\r\n\r\n";
}

export {
  computeAccept,
  handshakeResponse,
}
/* Crypto Not a pure module */
