// Generated by ReScript, PLEASE EDIT WITH CARE


let currentLevel = {
  contents: "Info"
};

function setLevel(level) {
  currentLevel.contents = level;
}

function log(level, msg) {
  let match = currentLevel.contents;
  let levelOk;
  switch (match) {
    case "Info" :
      switch (level) {
        case "Debug" :
          levelOk = false;
          break;
        case "Info" :
        case "Error" :
          levelOk = true;
          break;
      }
      break;
    case "Debug" :
      levelOk = true;
      break;
    case "Error" :
      switch (level) {
        case "Info" :
        case "Debug" :
          levelOk = false;
          break;
        case "Error" :
          levelOk = true;
          break;
      }
      break;
  }
  if (!levelOk) {
    return;
  }
  let levelStr;
  switch (level) {
    case "Info" :
      levelStr = "INFO";
      break;
    case "Debug" :
      levelStr = "DEBUG";
      break;
    case "Error" :
      levelStr = "ERROR";
      break;
  }
  let d = new Date();
  let ts = d.toISOString();
  let formatted = `[` + ts + `] ` + levelStr + `  ` + msg;
  switch (level) {
    case "Info" :
    case "Debug" :
      console.log(formatted);
      return;
    case "Error" :
      console.error(formatted);
      return;
  }
}

export {
  setLevel,
  log,
}
/* No side effect */
