// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../Node/Fs.res.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Node_Path from "../Node/Node_Path.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";

function resolveSafePath(base, requested) {
  try {
    let resolvedBase = Node_Path.resolve(base, "");
    let fullPath = Node_Path.join(resolvedBase, requested);
    let resolvedPath = Node_Path.resolve(fullPath, "");
    let rel = Node_Path.relative(resolvedBase, resolvedPath);
    if (rel.startsWith("..") || rel === "" && resolvedPath !== resolvedBase) {
      return;
    } else {
      return resolvedPath;
    }
  } catch (exn) {
    return;
  }
}

function replaceBackslashes(s) {
  return Js_string.replaceByRe(/\\/g, "/", s);
}

function matchesPattern(path, patterns) {
  let pathSegments = replaceBackslashes(path).split("/").filter(s => s !== "");
  return patterns.some(pattern => {
    let patternSegments = replaceBackslashes(pattern).split("/").filter(s => s !== "");
    let pLen = patternSegments.length;
    let pathLen = pathSegments.length;
    if (pLen === 0 || pLen > pathLen) {
      return false;
    }
    let _i = 0;
    while (true) {
      let i = _i;
      if ((i + pLen | 0) > pathLen) {
        return false;
      }
      let checkSeg = _j => {
        while (true) {
          let j = _j;
          if (j >= pLen) {
            return true;
          }
          let pathSeg = Stdlib_Option.getOr(pathSegments[i + j | 0], "");
          let patSeg = Stdlib_Option.getOr(patternSegments[j], "");
          if (pathSeg !== patSeg) {
            return false;
          }
          _j = j + 1 | 0;
          continue;
        };
      };
      if (checkSeg(0)) {
        return true;
      }
      _i = i + 1 | 0;
      continue;
    };
  });
}

function hasSymlinkPrefix(base, target) {
  let resolvedBase = Node_Path.resolve(base, "");
  let resolvedTarget = Node_Path.resolve(target, "");
  let rel = Node_Path.relative(resolvedBase, resolvedTarget);
  if (rel.startsWith("..")) {
    return Promise.resolve(false);
  }
  let segments = rel.split("/").filter(s => s !== "");
  let walk = (current, idx) => {
    if (idx >= segments.length) {
      return Promise.resolve(false);
    }
    let next = Node_Path.join(current, Stdlib_Option.getOr(segments[idx], ""));
    return Stdlib_Promise.$$catch(Fs.lstat(next).then(stat => {
      if (Fs.statIsSymlink(stat)) {
        return Promise.resolve(true);
      } else {
        return walk(next, idx + 1 | 0);
      }
    }), _error => Promise.resolve(false));
  };
  return walk(resolvedBase, 0);
}

export {
  resolveSafePath,
  matchesPattern,
  hasSymlinkPrefix,
}
/* Fs Not a pure module */
