// Generated by ReScript, PLEASE EDIT WITH CARE


let securityHeaders = [
  [
    "x-content-type-options",
    "nosniff"
  ],
  [
    "x-frame-options",
    "DENY"
  ],
  [
    "referrer-policy",
    "no-referrer"
  ],
  [
    "permissions-policy",
    "camera=(), microphone=(), geolocation=()"
  ],
  [
    "cross-origin-opener-policy",
    "same-origin"
  ],
  [
    "cross-origin-resource-policy",
    "same-origin"
  ],
  [
    "x-permitted-cross-domain-policies",
    "none"
  ],
  [
    "content-security-policy",
    "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:"
  ]
];

function isSecurityHeaderKey(name) {
  if (name === "x-content-type-options" || name === "x-frame-options" || name === "referrer-policy" || name === "permissions-policy" || name === "cross-origin-opener-policy" || name === "cross-origin-resource-policy" || name === "x-permitted-cross-domain-policies") {
    return true;
  } else {
    return name === "content-security-policy";
  }
}

function withSecurityHeaders(existing) {
  let filtered = existing.filter(param => !isSecurityHeaderKey(param[0]));
  return filtered.concat(securityHeaders);
}

export {
  securityHeaders,
  withSecurityHeaders,
}
/* No side effect */
