// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";

function matchesIgnorePattern(path, patterns) {
  let lower = path.toLowerCase();
  return patterns.some(p => {
    let pl = p.toLowerCase();
    if (!Js_string.includes("*", pl)) {
      return Js_string.includes(pl, lower);
    }
    let go = (s, _i, _acc) => {
      while (true) {
        let acc = _acc;
        let i = _i;
        if (i >= s.length) {
          return acc;
        }
        let c = s[i];
        if (c === undefined) {
          return acc;
        }
        let acc2 = c === "*" ? acc : acc + String(c);
        _acc = acc2;
        _i = i + 1 | 0;
        continue;
      };
    };
    let globRe = go(pl, 0, "");
    let startsStar = Js_string.startsWith("*", p);
    let endsStar = Js_string.endsWith("*", p);
    if (startsStar && endsStar) {
      return Js_string.includes(globRe, lower);
    } else if (startsStar) {
      return Js_string.endsWith(globRe, lower);
    } else if (endsStar) {
      return Js_string.startsWith(globRe, lower);
    } else {
      return lower === pl;
    }
  });
}

export {
  matchesIgnorePattern,
}
/* No side effect */
