// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rules from "./Rules.res.js";
import * as Timers from "../Node/Timers.res.js";
import * as FsWatch from "../Node/FsWatch.res.js";
import * as IgnoreMatcher from "./IgnoreMatcher.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function start(dir, ignorePatterns, enableLiveReload, restartOnChange, onReload, onRestart) {
  let lastRestartAt = {
    contents: 0.0
  };
  let h = {
    watcher: null,
    cancelled: false,
    processing: false,
    pendingTimeoutId: undefined,
    _emit: param => {}
  };
  let checkCooldown = () => {
    let now = Date.now();
    if (now - lastRestartAt.contents < 1000.0) {
      return false;
    } else {
      lastRestartAt.contents = now;
      return true;
    }
  };
  let onEvent = event => {
    if (typeof event !== "object") {
      return;
    }
    if (event.TAG !== "Modified") {
      return;
    }
    if (h.cancelled || h.processing) {
      return;
    }
    let filename = event._0;
    h.processing = true;
    if (IgnoreMatcher.matchesIgnorePattern(filename, ignorePatterns)) {
      h.processing = false;
      return;
    }
    let id = h.pendingTimeoutId;
    if (id !== undefined) {
      Timers.clearTimeout(Primitive_option.valFromOption(id));
    }
    let timeoutId = Timers.setTimeout(() => {
      if (h.cancelled) {
        h.pendingTimeoutId = undefined;
        h.processing = false;
        return;
      }
      let action = restartOnChange ? "Restart" : Rules.decide(filename);
      switch (action) {
        case "Restart" :
          if (checkCooldown()) {
            if (enableLiveReload) {
              onReload();
            }
            onRestart();
          }
          break;
        case "BrowserReload" :
          if (enableLiveReload) {
            onReload();
          }
          break;
        case "Ignore" :
          break;
      }
      h.pendingTimeoutId = undefined;
      h.processing = false;
    }, 500);
    h.pendingTimeoutId = Primitive_option.some(timeoutId);
  };
  h._emit = onEvent;
  let watcher = FsWatch.startWatcher(dir, {
    recursive: true
  }, onEvent);
  h.watcher = watcher;
  return h;
}

function cancel(h) {
  h.cancelled = true;
  FsWatch.close(h.watcher);
  let id = h.pendingTimeoutId;
  if (id !== undefined) {
    Timers.clearTimeout(Primitive_option.valFromOption(id));
  }
  h.pendingTimeoutId = undefined;
  h.processing = false;
}

function _testEmit(h, event) {
  h._emit(event);
}

export {
  start,
  cancel,
  _testEmit,
}
/* FsWatch Not a pure module */
