// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "../Node/Process.res.js";
import * as Process_spawn from "../Node/Process_spawn.res.js";

function reload(execPath, entrypoint, argv) {
  let childArgs = [entrypoint].concat(argv);
  let spawnResult = Process_spawn.callSpawn(execPath, childArgs, {
    stdio: "inherit",
    shell: false
  });
  if (spawnResult.TAG === "Ok") {
    return Process.exit(0);
  }
  console.error("[Restart] failed to spawn");
  Process.exit(1);
}

export {
  reload,
}
/* Process Not a pure module */
