// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "../Node/Process.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Process_spawn from "../Node/Process_spawn.res.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function reload(execPath, entrypoint, argv) {
  let childArgs = [entrypoint].concat(argv);
  let spawnResult;
  try {
    spawnResult = {
      TAG: "Ok",
      _0: Process_spawn.spawn.contents(execPath, childArgs, {
        stdio: "inherit",
        shell: false
      })
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    let m = Stdlib_JsExn.message(e);
    let msg = m !== undefined ? m : "unknown spawn error";
    spawnResult = {
      TAG: "Error",
      _0: msg
    };
  }
  if (spawnResult.TAG === "Ok") {
    return Process.exit(0);
  }
  console.error("[Restart] failed to spawn");
  Process.exit(1);
}

export {
  reload,
}
/* Process Not a pure module */
