// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "../Node/Process.res.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function reload(execPath, entrypoint, argv) {
  let childArgs = [entrypoint].concat(argv);
  let spawnResult;
  try {
    spawnResult = {
      TAG: "Ok",
      _0: Process.spawn(execPath, childArgs, {
        stdio: "inherit",
        shell: false
      })
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    spawnResult = {
      TAG: "Error",
      _0: e
    };
  }
  if (spawnResult.TAG === "Ok") {
    let child = spawnResult._0;
    let didExit = {
      contents: false
    };
    let ensureExit = code => {
      if (!didExit.contents) {
        didExit.contents = true;
        return Process.exit(code);
      }
    };
    Process.onError(child, _err => {
      console.error("[Restart] subprocess error");
      ensureExit(1);
    });
    Process.onChildExit(child, (code, _signal) => {
      if (code !== undefined && code !== 0) {
        return ensureExit(code);
      } else {
        return ensureExit(0);
      }
    });
    return;
  }
  console.error("[Restart] failed to spawn");
  Process.exit(1);
}

export {
  reload,
}
/* Process Not a pure module */
