// Generated by ReScript, PLEASE EDIT WITH CARE


function decide(filename) {
  let lname = filename.toLowerCase();
  if (lname.includes("deno.json") || lname.includes("deno.lock") || lname.includes("package.json") || lname.includes(".ts") || lname.includes(".js") || lname.includes(".mjs") || lname.includes(".json") || lname.includes(".toml") || lname.includes(".yaml") || lname.includes(".yml")) {
    return "Restart";
  } else if (lname.includes(".html") || lname.includes(".htm") || lname.includes(".css") || lname.includes(".scss") || lname.includes(".sass") || lname.includes(".less") || lname.includes(".jsx") || lname.includes(".tsx") || lname.includes(".vue") || lname.includes(".svelte") || lname.includes(".md") || lname.includes(".png") || lname.includes(".jpg") || lname.includes(".jpeg") || lname.includes(".gif") || lname.includes(".svg") || lname.includes(".webp") || lname.includes(".ico") || lname.includes(".woff") || lname.includes(".woff2") || lname.includes(".ttf") || lname.includes(".eot")) {
    return "BrowserReload";
  } else {
    return "Ignore";
  }
}

export {
  decide,
}
/* No side effect */
