// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "./Node/Http.res.js";
import * as WsHub from "./Hub/WsHub.res.js";
import * as Parser from "./Cfg/Parser.res.js";
import * as Monitor from "./Watcher/Monitor.res.js";
import * as Process from "./Node/Process.res.js";
import * as ParseError from "./Cfg/ParseError.res.js";
import * as AbortController from "./Node/AbortController.res.js";

function notImplementedHandler(_req) {
  return Promise.resolve({
    TAG: "Respond",
    _0: {
      status: 501,
      headers: [[
          "content-type",
          "text/plain; charset=utf-8"
        ]],
      body: "Empty"
    }
  });
}

function warnRestart() {
  console.warn("[Httpath] restart-on-change requested but Restart module is not yet implemented");
}

function start(handler, config) {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let onWsUpgrade = (_req, socket, _head) => {
    WsHub.register(socket);
    return Promise.resolve();
  };
  Http.startServer(config.port, config.hostname, handler, onWsUpgrade, sig);
  let monitorHandle = Monitor.start(config.directory, config.ignorePatterns, config.enableLiveReload, config.restartOnChange, WsHub.notifyReload, warnRestart);
  let shutdownResolve = {
    contents: undefined
  };
  let shutdownPromise = new Promise((resolve, _reject) => {
    shutdownResolve.contents = resolve;
  });
  let shutdown = () => {
    Monitor.cancel(monitorHandle);
    AbortController.abort(controller);
    let r = shutdownResolve.contents;
    if (r !== undefined) {
      return r();
    }
  };
  let sigintHandler = () => shutdown();
  let sigtermHandler = () => shutdown();
  process.on("SIGINT", sigintHandler);
  process.on("SIGTERM", sigtermHandler);
  return shutdownPromise.then(() => {
    process.off("SIGINT", sigintHandler);
    process.off("SIGTERM", sigtermHandler);
    Process.exit(0);
    return Promise.resolve();
  });
}

function main() {
  let args = Process.argv.slice(2, Process.argv.length);
  let config = Parser.parse(args);
  if (config.TAG === "Ok") {
    return start(notImplementedHandler, config._0);
  }
  let e = config._0;
  if (typeof e !== "object") {
    console.log("Usage: httpath [-d <dir>] [-p <port>] [-i <patterns>] [--no-listing] [--no-live-reload] [-r] [-l] [--allow-protected-dir] [--log <level>]");
    Process.exit(0);
    return Promise.resolve();
  }
  console.error("Error: " + ParseError.toString(e));
  Process.exit(1);
  return Promise.resolve();
}

export {
  main,
  start,
}
/* Http Not a pure module */
