// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "./Node/Http.res.js";
import * as Types from "./Types.res.js";
import * as WsHub from "./Hub/WsHub.res.js";
import * as Buffer from "./Node/Buffer.res.js";
import * as Parser from "./Cfg/Parser.res.js";
import * as Timers from "./Node/Timers.res.js";
import * as Handler from "./Server/Handler.res.js";
import * as Monitor from "./Watcher/Monitor.res.js";
import * as Process from "./Node/Process.res.js";
import * as Restart from "./Watcher/Restart.res.js";
import * as ParseError from "./Cfg/ParseError.res.js";
import * as WsHandshake from "./Http/WsHandshake.res.js";
import * as AbortController from "./Node/AbortController.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function start(handler, config) {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let onWsUpgrade = (req, socket, _head) => {
    let key = Types.getHeader(req.headers, "sec-websocket-key");
    if (key !== undefined) {
      let accept = WsHandshake.computeAccept(key);
      let response = WsHandshake.handshakeResponse(accept);
      return Http.socketWriteBuffer(socket, Buffer.fromString(response, "utf8")).then(result => {
        if (result.TAG === "Ok") {
          WsHub.register(socket);
        } else {
          Http.socketDestroy(socket);
        }
        return Promise.resolve();
      });
    }
    Http.socketDestroy(socket);
    return Promise.resolve();
  };
  let match = Http.startServer(config.port, config.hostname, handler, onWsUpgrade, sig);
  let server = match.server;
  let monitorHandle = {
    contents: undefined
  };
  let onRestart = () => {
    Http.closeServer(server);
    let h = monitorHandle.contents;
    if (h !== undefined) {
      Monitor.cancel(Primitive_option.valFromOption(h));
    }
    WsHub.closeAll();
    Restart.reload(Process.execPath, "bin.mjs", Process.argv.slice(2, Process.argv.length));
  };
  let handle = Monitor.start(config.directory, config.ignorePatterns, config.enableLiveReload, config.restartOnChange, WsHub.notifyReload, onRestart);
  monitorHandle.contents = Primitive_option.some(handle);
  let shutdown = () => {
    let h = monitorHandle.contents;
    if (h !== undefined) {
      Monitor.cancel(Primitive_option.valFromOption(h));
    }
    AbortController.abort(controller);
    Timers.setTimeout(() => Process.exit(0), 500);
  };
  let sigintHandler = () => shutdown();
  let sigtermHandler = () => shutdown();
  process.on("SIGINT", sigintHandler);
  process.on("SIGTERM", sigtermHandler);
  return match.closed.then(() => {
    process.off("SIGINT", sigintHandler);
    process.off("SIGTERM", sigtermHandler);
    Process.exit(0);
    return Promise.resolve();
  });
}

function main() {
  let args = Process.argv.slice(2, Process.argv.length);
  let config = Parser.parse(args);
  if (config.TAG === "Ok") {
    let config$1 = config._0;
    let handler = Handler.make(config$1);
    return start(handler, config$1);
  }
  let e = config._0;
  if (typeof e !== "object") {
    console.log("Usage: httpath [-d <dir>] [-p <port>] [-i <patterns>] [--no-listing] [--no-live-reload] [-r] [-l] [--allow-protected-dir] [--log <level>]");
    Process.exit(0);
    return Promise.resolve();
  }
  console.error("Error: " + ParseError.toString(e));
  Process.exit(1);
  return Promise.resolve();
}

export {
  main,
  start,
}
/* Http Not a pure module */
