// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function getHeader(headers, name) {
  return Belt_Option.map(Belt_Array.getBy(headers, param => param[0] === name), param => param[1]);
}

let liveReloadEndpoint = "/livereload";

let liveReloadMessage = "reload";

export {
  liveReloadEndpoint,
  liveReloadMessage,
  getHeader,
}
/* No side effect */
