// Generated by ReScript, PLEASE EDIT WITH CARE


let liveReloadEndpoint = "/livereload";

let liveReloadMessage = "reload";

export {
  liveReloadEndpoint,
  liveReloadMessage,
}
/* No side effect */
