// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as AbortController from "../../src/Node/AbortController.res.js";

function makeAbortCallback() {
  let count = {
    contents: 0
  };
  let fn = () => {
    count.contents = count.contents + 1 | 0;
  };
  return [
    fn,
    count
  ];
}

Test.test("AbortController.make creates a controller", () => {
  AbortController.make();
  Test.assertion("make returns a controller instance", "=", (a, b) => a === b, true, true);
});

Test.test("signal is not aborted immediately after make", () => {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let match = makeAbortCallback();
  AbortController.onAbort(sig, match[0]);
  Test.assertion("signal onabort not yet fired after construction", "=", (a, b) => a === b, match[1].contents, 0);
});

Test.test("abort() fires the onabort callback exactly once", () => {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let match = makeAbortCallback();
  AbortController.onAbort(sig, match[0]);
  AbortController.abort(controller);
  Test.assertion("onabort called exactly once after abort()", "=", (a, b) => a === b, match[1].contents, 1);
});

Test.test("calling abort twice does not double-fire onabort", () => {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let match = makeAbortCallback();
  AbortController.onAbort(sig, match[0]);
  AbortController.abort(controller);
  AbortController.abort(controller);
  Test.assertion("onabort fires exactly once even with double abort", "=", (a, b) => a === b, match[1].contents, 1);
});

Test.test("onAbort callback is called with unit", () => {
  let controller = AbortController.make();
  let sig = AbortController.signal(controller);
  let called = {
    contents: false
  };
  let cb = () => {
    called.contents = true;
  };
  AbortController.onAbort(sig, cb);
  AbortController.abort(controller);
  Test.assertion("callback was called", "=", (a, b) => a === b, called.contents, true);
});

export {
  makeAbortCallback,
}
/*  Not a pure module */
