// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Config from "../../src/Cli/Config.res.js";

Test.test("Config.default has correct directory", () => {
  let dir = Config.default.directory;
  Test.assertion("directory is a non-empty string", "=", (a, b) => a === b, dir.length > 0, true);
});

Test.test("Config.default hostname is 127.0.0.1", () => Test.assertion("hostname defaults to 127.0.0.1", "=", (a, b) => a === b, Config.default.hostname, "127.0.0.1"));

Test.test("Config.default port is 8080", () => Test.assertion("port defaults to 8080", "=", (a, b) => a === b, Config.default.port, 8080));

Test.test("Config.default ignorePatterns has .git, node_modules, .DS_Store", () => {
  let patterns = Config.default.ignorePatterns;
  let hasGit = patterns.some(p => p === ".git");
  let hasNodeModules = patterns.some(p => p === "node_modules");
  let hasDSStore = patterns.some(p => p === ".DS_Store");
  Test.assertion("ignorePatterns contains .git", "=", (a, b) => a === b, hasGit, true);
  Test.assertion("ignorePatterns contains node_modules", "=", (a, b) => a === b, hasNodeModules, true);
  Test.assertion("ignorePatterns contains .DS_Store", "=", (a, b) => a === b, hasDSStore, true);
});

Test.test("Config.default enableDirectoryListing is false", () => Test.assertion("enableDirectoryListing defaults to false", "=", (a, b) => a === b, Config.default.enableDirectoryListing, false));

Test.test("Config.default logLevel is Info", () => Test.assertion("logLevel defaults to Info", "=", (a, b) => a === b, Config.default.logLevel, "Info"));

Test.test("Config.default enableLiveReload is true", () => Test.assertion("enableLiveReload defaults to true", "=", (a, b) => a === b, Config.default.enableLiveReload, true));

Test.test("Config.default restartOnChange is false", () => Test.assertion("restartOnChange defaults to false", "=", (a, b) => a === b, Config.default.restartOnChange, false));

Test.test("Config.default lan is false", () => Test.assertion("lan defaults to false", "=", (a, b) => a === b, Config.default.lan, false));

Test.test("Config.default allowProtectedDir is false", () => Test.assertion("allowProtectedDir defaults to false", "=", (a, b) => a === b, Config.default.allowProtectedDir, false));

Test.test("Config.t is a record with 10 fields", () => {
  let d = Config.default.directory;
  let h = Config.default.hostname;
  let p = Config.default.port;
  let ip = Config.default.ignorePatterns;
  let edl = Config.default.enableDirectoryListing;
  let elr = Config.default.enableLiveReload;
  let roc = Config.default.restartOnChange;
  let lan = Config.default.lan;
  let apd = Config.default.allowProtectedDir;
  let allAccessible = d !== "" && h !== "" && p >= 0 && ip.length !== 0 && edl === false && elr === true && roc === false && lan === false && apd === false;
  Test.assertion("all 10 Config fields are accessible", "=", (a, b) => a === b, allAccessible, true);
});

/*  Not a pure module */
