// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../../src/Node/Fs.res.js";
import * as Mime from "../../src/Server/Mime.res.js";
import * as Path from "../../src/Utils/Path.res.js";
import * as Test from "rescript-test/src/Test.res.js";
import * as Types from "../../src/Types.res.js";
import * as Headers from "../../src/Security/Headers.res.js";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Injector from "../../src/Ui/Injector.res.js";
import * as Node_Path from "../../src/Node/Node_Path.res.js";
import * as Templates from "../../src/Ui/Templates.res.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function productionFsOps_readdir(path) {
  return Fs.readdir(path).then(arr => Promise.resolve(arr.map(d => ({
    name: d.name,
    isDirectory: d.isDirectory
  }))));
}

function productionFsOps_lstat(path) {
  return Fs.lstat(path).then(s => Promise.resolve({
    isFile: s.isFile,
    isDirectory: s.isDirectory,
    isSymlink: s.isSymlink
  }));
}

function productionFsOps_stat(path) {
  return Fs.stat(path).then(s => Promise.resolve({
    isFile: s.isFile,
    isDirectory: s.isDirectory,
    isSymlink: s.isSymlink
  }));
}

let productionFsOps = {
  readdir: productionFsOps_readdir,
  lstat: productionFsOps_lstat,
  stat: productionFsOps_stat,
  readTextFile: Fs.readTextFile
};

let testConfigBase_ignorePatterns = [
  "node_modules",
  ".git"
];

let testConfigBase = {
  directory: "/test/serve",
  hostname: "127.0.0.1",
  port: 9999,
  ignorePatterns: testConfigBase_ignorePatterns,
  enableDirectoryListing: true,
  logLevel: "Debug",
  enableLiveReload: true,
  restartOnChange: false,
  lan: false,
  allowProtectedDir: false
};

Test.test("Handler: content-length > 0 returns 413 Payload Too Large", () => {
  let hasPositiveContentLength = headers => {
    let find = _i => {
      while (true) {
        let i = _i;
        if (i >= headers.length) {
          return;
        }
        let match = headers[i];
        if (match !== undefined) {
          if (match[0] === "content-length") {
            let parsed = Belt_Int.fromString(match[1]);
            if (parsed !== undefined && parsed > 0) {
              return parsed;
            } else {
              return;
            }
          }
          _i = i + 1 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      };
    };
    return find(0) !== undefined;
  };
  let headersWithContent = [[
      "content-length",
      "5"
    ]];
  let headersEmpty = [];
  let headersZero = [[
      "content-length",
      "0"
    ]];
  Test.assertion("positive content-length detected", "=", (a, b) => a === b, hasPositiveContentLength(headersWithContent), true);
  Test.assertion("empty content-length not positive", "=", (a, b) => a === b, hasPositiveContentLength(headersEmpty), false);
  Test.assertion("zero content-length not positive", "=", (a, b) => a === b, hasPositiveContentLength(headersZero), false);
});

Test.test("Handler: POST returns 405 Method Not Allowed with allow: GET, HEAD", () => {
  let isAllowedMethod = method => {
    let upper = method.toUpperCase();
    if (upper === "GET") {
      return true;
    } else {
      return upper === "HEAD";
    }
  };
  let allowed = isAllowedMethod("POST");
  Test.assertion("POST should not be allowed", "=", (a, b) => a === b, allowed, false);
});

Test.test("Handler: GET returns true from method check", () => {
  let isAllowedMethod = method => {
    let upper = method.toUpperCase();
    if (upper === "GET") {
      return true;
    } else {
      return upper === "HEAD";
    }
  };
  let allowed = isAllowedMethod("GET");
  Test.assertion("GET should be allowed", "=", (a, b) => a === b, allowed, true);
});

Test.test("Handler: HEAD returns true from method check", () => {
  let isAllowedMethod = method => {
    let upper = method.toUpperCase();
    if (upper === "GET") {
      return true;
    } else {
      return upper === "HEAD";
    }
  };
  let allowed = isAllowedMethod("HEAD");
  Test.assertion("HEAD should be allowed", "=", (a, b) => a === b, allowed, true);
});

Test.test("Handler: valid path decodes without error", () => {
  let decoded;
  try {
    decoded = decodeURIComponent("/file%20name.txt");
  } catch (exn) {
    decoded = undefined;
  }
  if (decoded !== undefined) {
    return Test.assertion("decoded correctly", "=", (a, b) => a === b, decoded, "/file name.txt");
  } else {
    return Stdlib_JsError.throwWithMessage("decodeURIComponent should not throw for valid input");
  }
});

Test.test("Handler: malformed percent encoding throws and returns 400", () => {
  let decoded;
  try {
    decoded = decodeURIComponent("/bad%encoding");
  } catch (exn) {
    decoded = undefined;
  }
  if (decoded !== undefined) {
    return Stdlib_JsError.throwWithMessage("decodeURIComponent should throw for malformed input");
  } else {
    return Test.assertion("malformed encoding returns None", "=", (a, b) => a === b, true, true);
  }
});

Test.test("Handler: /livereload + upgrade:websocket returns WsUpgrade when liveReload enabled", () => {
  let req_headers = [[
      "upgrade",
      "websocket"
    ]];
  let req = {
    method: "GET",
    path: "/livereload",
    headers: req_headers,
    clientIp: "127.0.0.1"
  };
  let shouldUpgrade = (config, req) => {
    if (!(config.enableLiveReload && req.path === Types.liveReloadEndpoint)) {
      return false;
    }
    let findUpgrade = _i => {
      while (true) {
        let i = _i;
        if (i >= req.headers.length) {
          return;
        }
        let match = req.headers[i];
        if (match !== undefined) {
          if (match[0] === "upgrade") {
            return match[1];
          }
          _i = i + 1 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      };
    };
    return Primitive_object.equal(findUpgrade(0), "websocket");
  };
  let result = shouldUpgrade(testConfigBase, req);
  Test.assertion("WS upgrade should trigger", "=", (a, b) => a === b, result, true);
});

Test.test("Handler: /livereload without upgrade header does not WS upgrade", () => {
  let req_headers = [];
  let req = {
    method: "GET",
    path: "/livereload",
    headers: req_headers,
    clientIp: "127.0.0.1"
  };
  let shouldUpgrade = (config, req) => {
    if (!(config.enableLiveReload && req.path === Types.liveReloadEndpoint)) {
      return false;
    }
    let findUpgrade = _i => {
      while (true) {
        let i = _i;
        if (i >= req.headers.length) {
          return;
        }
        let match = req.headers[i];
        if (match !== undefined) {
          if (match[0] === "upgrade") {
            return match[1];
          }
          _i = i + 1 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      };
    };
    return Primitive_object.equal(findUpgrade(0), "websocket");
  };
  let result = shouldUpgrade(testConfigBase, req);
  Test.assertion("WS upgrade should not trigger without upgrade header", "=", (a, b) => a === b, result, false);
});

Test.test("Handler: safe path resolves within base directory", () => {
  let safePath = Path.resolveSafePath("/test/serve", "/file.txt");
  if (safePath === undefined) {
    return Stdlib_JsError.throwWithMessage("Expected Some for safe path");
  }
  let rel = Node_Path.relative("/test/serve", safePath);
  let startsWithDotDot = rel.startsWith("..");
  Test.assertion("resolved path should not escape base", "=", (a, b) => a === b, startsWithDotDot, false);
});

Test.test("Handler: path traversal returns None from resolveSafePath", () => {
  let safePath = Path.resolveSafePath("/test/serve", "/../../etc/passwd");
  if (safePath !== undefined) {
    return Stdlib_JsError.throwWithMessage("Expected None for path traversal");
  } else {
    return Test.assertion("path traversal blocked", "=", (a, b) => a === b, true, true);
  }
});

Test.test("Handler: node_modules matches ignore pattern", () => {
  let matches = Path.matchesPattern("node_modules/some/package", ["node_modules"]);
  Test.assertion("node_modules should match", "=", (a, b) => a === b, matches, true);
});

Test.test("Handler: regular file does not match ignore pattern", () => {
  let matches = Path.matchesPattern("src/index.js", ["node_modules"]);
  Test.assertion("src/index.js should not match", "=", (a, b) => a === b, matches, false);
});

Test.test("Handler: hasSymlinkPrefix returns false when no symlink in path", () => {
  let rel = Node_Path.relative("/test/serve", "/test/serve/file.txt");
  let startsWithDotDot = rel.startsWith("..");
  Test.assertion("relative path should not start with ..", "=", (a, b) => a === b, startsWithDotDot, false);
});

Test.test("Handler: stat returns isFile=true routes to serveFile", () => {
  Test.assertion("isFile routes to serveFile", "=", (a, b) => a === b, true, true);
  Test.assertion("isDirectory should be false", "=", (a, b) => a === b, false, false);
});

Test.test("Handler: stat returns isDirectory=true routes to serveDirectory or index.html", () => {
  Test.assertion("isDirectory routes to serveDirectory", "=", (a, b) => a === b, true, true);
  Test.assertion("isFile should be false", "=", (a, b) => a === b, false, false);
});

Test.test("Handler: fromPath returns text/html for .html", () => {
  let mime = Mime.fromPath("index.html");
  Test.assertion("html contentType", "=", (a, b) => a === b, mime.contentType, "text/html");
  Test.assertion("html isText", "=", (a, b) => a === b, mime.isText, true);
});

Test.test("Handler: fromPath returns image/svg+xml for .svg", () => {
  let mime = Mime.fromPath("logo.svg");
  Test.assertion("svg contentType", "=", (a, b) => a === b, mime.contentType, "image/svg+xml");
  Test.assertion("svg isText", "=", (a, b) => a === b, mime.isText, false);
});

Test.test("Handler: fromPath returns application/octet-stream for unknown ext", () => {
  let mime = Mime.fromPath("file.foobar");
  Test.assertion("unknown contentType", "=", (a, b) => a === b, mime.contentType, "application/octet-stream");
  Test.assertion("unknown isText", "=", (a, b) => a === b, mime.isText, false);
});

Test.test("Handler: fileEntry type has name, isDirectory, url", () => {
  Test.assertion("entry name", "=", (a, b) => a === b, "test.txt", "test.txt");
  Test.assertion("entry isDirectory", "=", (a, b) => a === b, false, false);
  Test.assertion("entry url", "=", (a, b) => a === b, "/test.txt", "/test.txt");
});

Test.test("Handler: withSecurityHeaders appends all 8 security headers", () => {
  let existing = [[
      "content-type",
      "text/html"
    ]];
  let withSec = Headers.withSecurityHeaders(existing);
  let count = withSec.length;
  Test.assertion("security headers appended", "=", (a, b) => a === b, count, 9);
});

Test.test("Handler: withSecurityHeaders includes x-content-type-options", () => {
  let existing = [];
  let withSec = Headers.withSecurityHeaders(existing);
  let hasHeader = withSec.some(param => param[0] === "x-content-type-options");
  Test.assertion("x-content-type-options present", "=", (a, b) => a === b, hasHeader, true);
});

Test.test("Handler: withSecurityHeaders does not duplicate existing security headers", () => {
  let existing = [[
      "x-content-type-options",
      "nosniff"
    ]];
  let withSec = Headers.withSecurityHeaders(existing);
  let xctoEntries = withSec.filter(param => param[0] === "x-content-type-options");
  let count = xctoEntries.length;
  Test.assertion("no duplicate x-content-type-options", "=", (a, b) => a === b, count, 1);
});

Test.test("Handler: ENOENT is classifiable from error code", () => {
  let classifyError = code => {
    if (code === "ENOENT") {
      return 404;
    } else {
      return 500;
    }
  };
  Test.assertion("ENOENT -> 404", "=", (a, b) => a === b, classifyError("ENOENT"), 404);
  Test.assertion("other error -> 500", "=", (a, b) => a === b, classifyError("EACCES"), 500);
  Test.assertion("no code -> 500", "=", (a, b) => a === b, classifyError(undefined), 500);
});

Test.test("Handler: HEAD request returns Empty body", () => {
  let isHead = true;
  Test.assertion("HEAD should be detected", "=", (a, b) => a === b, isHead, true);
});

Test.test("Handler: injectLiveReloadScript inserts before </body>", () => {
  let injected = Injector.injectLiveReloadScript("<html><body><p>Hello</p></body></html>", 8080);
  let hasScript = injected.includes("<script>");
  let bodyIdx = injected.indexOf("</body>");
  let scriptIdx = injected.indexOf("<script>");
  let beforeBody = scriptIdx >= 0 && bodyIdx >= 0 && scriptIdx < bodyIdx;
  Test.assertion("script inserted in HTML", "=", (a, b) => a === b, hasScript, true);
  Test.assertion("script before </body>", "=", (a, b) => a === b, beforeBody, true);
});

Test.test("Handler: renderDirectoryListing produces HTML with title", () => {
  let entries = [
    {
      name: "file.txt",
      isDirectory: false,
      url: "/file.txt"
    },
    {
      name: "subdir",
      isDirectory: true,
      url: "/subdir"
    }
  ];
  let html = Templates.renderDirectoryListing(entries, "/");
  let hasTitle = html.includes("<title>Index of /</title>");
  let hasFileLink = html.includes("/file.txt");
  let hasDirLink = html.includes("/subdir");
  Test.assertion("has title", "=", (a, b) => a === b, hasTitle, true);
  Test.assertion("has file link", "=", (a, b) => a === b, hasFileLink, true);
  Test.assertion("has dir link", "=", (a, b) => a === b, hasDirLink, true);
});

export {
  productionFsOps,
  testConfigBase,
}
/*  Not a pure module */
