// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Types from "../../src/Types.res.js";
import * as Injector from "../../src/Ui/Injector.res.js";

Test.test("Injector.liveReloadScript: contains ws: protocol for http", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains ws:", "=", (a, b) => a === b, script.includes("ws:"), true);
});

Test.test("Injector.liveReloadScript: contains wss: protocol for https", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains wss:", "=", (a, b) => a === b, script.includes("wss:"), true);
});

Test.test("Injector.liveReloadScript: contains location.protocol check", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("checks location.protocol", "=", (a, b) => a === b, script.includes("window.location.protocol"), true);
});

Test.test("Injector.liveReloadScript: contains the livereload endpoint path", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains /livereload", "=", (a, b) => a === b, script.includes(Types.liveReloadEndpoint), true);
});

Test.test("Injector.liveReloadScript: contains the liveReloadMessage check", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains reload message check", "=", (a, b) => a === b, script.includes("if (event.data === '" + Types.liveReloadMessage + "')"), true);
});

Test.test("Injector.liveReloadScript: contains reload() call", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains window.location.reload", "=", (a, b) => a === b, script.includes("window.location.reload()"), true);
});

Test.test("Injector.liveReloadScript: contains 1000ms reconnect delay", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("contains 1000ms timeout", "=", (a, b) => a === b, script.includes("setTimeout(connect, 1000)"), true);
});

Test.test("Injector.liveReloadScript: is wrapped in IIFE", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("starts with (() =>", "=", (a, b) => a === b, script.includes("(() => {"), true);
  Test.assertion("ends with })();", "=", (a, b) => a === b, script.includes("})();"), true);
});

Test.test("Injector.liveReloadScript: wrapped in script tag", () => {
  let script = Injector.liveReloadScript(5173);
  Test.assertion("starts with <script>", "=", (a, b) => a === b, script.includes("<script>"), true);
  Test.assertion("ends with </script>", "=", (a, b) => a === b, script.includes("</script>"), true);
});

Test.test("injectLiveReloadScript: inserts before </body> when present", () => {
  let result = Injector.injectLiveReloadScript("<html><body><p>Hello</p></body></html>", 5173);
  Test.assertion("contains </body>", "=", (a, b) => a === b, result.includes("</body>"), true);
  let scriptPos = result.indexOf("<script>");
  let bodyPos = result.indexOf("</body>");
  Test.assertion("script before </body>", "=", (a, b) => a < b, scriptPos, bodyPos);
  let parts = result.split("<script>");
  let count = parts.length - 1 | 0;
  Test.assertion("exactly one script tag", "=", (a, b) => a === b, count, 1);
});

Test.test("injectLiveReloadScript: inserts before </html> when no </body>", () => {
  let result = Injector.injectLiveReloadScript("<html><head></head><p>Hello</p></html>", 5173);
  Test.assertion("contains </html>", "=", (a, b) => a === b, result.includes("</html>"), true);
  let scriptPos = result.indexOf("<script>");
  let htmlEndPos = result.indexOf("</html>");
  Test.assertion("script before </html>", "=", (a, b) => a < b, scriptPos, htmlEndPos);
});

Test.test("injectLiveReloadScript: appends when neither </body> nor </html>", () => {
  let result = Injector.injectLiveReloadScript("<p>Hello</p>", 5173);
  Test.assertion("contains original p tag", "=", (a, b) => a === b, result.includes("<p>Hello</p>"), true);
  let pEnd = result.indexOf("</p>") + 5 | 0;
  let scriptPos = result.indexOf("<script>");
  Test.assertion("script at or after original content", "=", (a, b) => a >= b, scriptPos, pEnd);
});

Test.test("injectLiveReloadScript: does single replacement only", () => {
  let result = Injector.injectLiveReloadScript("<html><body><p>Hello</p></body><body><p>Another</p></body></html>", 5173);
  let parts = result.split("</body>");
  let count = parts.length - 1 | 0;
  Test.assertion("exactly 2 body tags", "=", (a, b) => a === b, count, 2);
});

/*  Not a pure module */
