// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mime from "../../src/Server/Mime.res.js";
import * as Test from "rescript-test/src/Test.res.js";

Test.test("Mime.mimeFor('html') returns text/html, isText=true", () => {
  let m = Mime.mimeFor("html");
  Test.assertion("contentType is text/html", "=", (a, b) => a === b, m.contentType, "text/html");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('htm') returns text/html, isText=true", () => {
  let m = Mime.mimeFor("htm");
  Test.assertion("contentType is text/html", "=", (a, b) => a === b, m.contentType, "text/html");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('css') returns text/css, isText=true", () => {
  let m = Mime.mimeFor("css");
  Test.assertion("contentType is text/css", "=", (a, b) => a === b, m.contentType, "text/css");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('js') returns text/javascript", () => {
  let m = Mime.mimeFor("js");
  Test.assertion("contentType is text/javascript", "=", (a, b) => a === b, m.contentType, "text/javascript");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('mjs') returns text/javascript", () => {
  let m = Mime.mimeFor("mjs");
  Test.assertion("contentType is text/javascript", "=", (a, b) => a === b, m.contentType, "text/javascript");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('json') returns application/json, isText=false", () => {
  let m = Mime.mimeFor("json");
  Test.assertion("contentType is application/json", "=", (a, b) => a === b, m.contentType, "application/json");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('txt') returns text/plain, isText=true", () => {
  let m = Mime.mimeFor("txt");
  Test.assertion("contentType is text/plain", "=", (a, b) => a === b, m.contentType, "text/plain");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.mimeFor('svg') returns image/svg+xml, isText=false", () => {
  let m = Mime.mimeFor("svg");
  Test.assertion("contentType is image/svg+xml", "=", (a, b) => a === b, m.contentType, "image/svg+xml");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('png') returns image/png", () => {
  let m = Mime.mimeFor("png");
  Test.assertion("contentType is image/png", "=", (a, b) => a === b, m.contentType, "image/png");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('jpg') returns image/jpeg", () => {
  let m = Mime.mimeFor("jpg");
  Test.assertion("contentType is image/jpeg", "=", (a, b) => a === b, m.contentType, "image/jpeg");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('jpeg') returns image/jpeg", () => {
  let m = Mime.mimeFor("jpeg");
  Test.assertion("contentType is image/jpeg", "=", (a, b) => a === b, m.contentType, "image/jpeg");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('gif') returns image/gif", () => {
  let m = Mime.mimeFor("gif");
  Test.assertion("contentType is image/gif", "=", (a, b) => a === b, m.contentType, "image/gif");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('webp') returns image/webp", () => {
  let m = Mime.mimeFor("webp");
  Test.assertion("contentType is image/webp", "=", (a, b) => a === b, m.contentType, "image/webp");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('ico') returns image/x-icon", () => {
  let m = Mime.mimeFor("ico");
  Test.assertion("contentType is image/x-icon", "=", (a, b) => a === b, m.contentType, "image/x-icon");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('wasm') returns application/wasm", () => {
  let m = Mime.mimeFor("wasm");
  Test.assertion("contentType is application/wasm", "=", (a, b) => a === b, m.contentType, "application/wasm");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('map') returns application/json", () => {
  let m = Mime.mimeFor("map");
  Test.assertion("contentType is application/json", "=", (a, b) => a === b, m.contentType, "application/json");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('unknown') returns application/octet-stream, isText=false", () => {
  let m = Mime.mimeFor("unknown");
  Test.assertion("contentType is application/octet-stream", "=", (a, b) => a === b, m.contentType, "application/octet-stream");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.mimeFor('woff2') returns application/octet-stream (REQ-MIME-3 parity gap)", () => {
  let m = Mime.mimeFor("woff2");
  Test.assertion("woff2 is octet-stream (not in fixed table)", "=", (a, b) => a === b, m.contentType, "application/octet-stream");
  Test.assertion("isText is false", "=", (a, b) => a === b, m.isText, false);
});

Test.test("Mime.fromPath('index.html') returns text/html, isText=true", () => {
  let m = Mime.fromPath("index.html");
  Test.assertion("fromPath html", "=", (a, b) => a === b, m.contentType, "text/html");
  Test.assertion("isText is true", "=", (a, b) => a === b, m.isText, true);
});

Test.test("Mime.fromPath('/foo/bar.css') returns text/css", () => {
  let m = Mime.fromPath("/foo/bar.css");
  Test.assertion("fromPath css", "=", (a, b) => a === b, m.contentType, "text/css");
});

Test.test("Mime.fromPath('file.MIME') is case-insensitive", () => {
  let m = Mime.fromPath("file.MIME");
  Test.assertion("MIME is treated as mime", "=", (a, b) => a === b, m.contentType, "application/octet-stream");
});

Test.test("Mime.fromPath('x.html') returns html", () => {
  let m = Mime.fromPath("x.html");
  Test.assertion("fromPath strips path, gets html", "=", (a, b) => a === b, m.contentType, "text/html");
});

Test.test("Mime.fromPath('noextension') returns octet-stream", () => {
  let m = Mime.fromPath("noextension");
  Test.assertion("no extension is octet-stream", "=", (a, b) => a === b, m.contentType, "application/octet-stream");
});

/*  Not a pure module */
