// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Monitor from "../../src/Watcher/Monitor.res.js";
import * as Monitor_socketMjs from "./monitor_socket.mjs";

function makeFakeClock(prim) {
  Monitor_socketMjs.makeFakeClock();
}

function advanceTime(prim) {
  Monitor_socketMjs.advanceTime(prim);
}

function restoreClock(prim) {
  Monitor_socketMjs.restoreClock();
}

function makeReloadCallback() {
  let count = {
    contents: 0
  };
  let fn = () => {
    count.contents = count.contents + 1 | 0;
  };
  return [
    fn,
    count
  ];
}

function makeRestartCallback() {
  let count = {
    contents: 0
  };
  let fn = () => {
    count.contents = count.contents + 1 | 0;
  };
  return [
    fn,
    count
  ];
}

Test.test("Monitor.start returns a handle", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [
    ".git",
    "node_modules"
  ], true, false, match[0], match$1[0]);
  Test.assertion("start returns a handle", "=", (a, b) => a === b, true, true);
  Monitor.cancel(handle);
});

Test.test("Monitor.cancel does not throw on valid handle", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [".git"], true, false, match[0], match$1[0]);
  Test.doesNotThrow("cancel does not throw", () => Monitor.cancel(handle));
});

Test.test("Monitor.cancel is idempotent", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, false, match[0], match$1[0]);
  Monitor.cancel(handle);
  Test.doesNotThrow("second cancel does not throw", () => Monitor.cancel(handle));
});

Test.test("Monitor.start accepts all required labeled args", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [
    ".git",
    "node_modules",
    ".DS_Store"
  ], true, true, match[0], match$1[0]);
  Test.assertion("start accepts all labeled args", "=", (a, b) => a === b, true, true);
  Monitor.cancel(handle);
});

Test.test("Debounce collapses rapid events into one dispatch (REQ-FW-2)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("only one dispatch fires despite 5 rapid events", "=", (a, b) => a === b, match[1].contents, 1);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("BrowserReload dispatches onReload when enableLiveReload=true (REQ-FW-5)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("onReload called once for HTML file with enableLiveReload=true", "=", (a, b) => a === b, match[1].contents, 1);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("Restart dispatches onRestart for JS file (REQ-FW-6)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, false, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "app.js"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("onRestart called once for JS file", "=", (a, b) => a === b, match$1[1].contents, 1);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("Re-entrancy guard drops events during in-flight dispatch (REQ-FW-7)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, true, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "style.css"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("only one dispatch fires even with concurrent events", "=", (a, b) => a === b, match$1[1].contents, 1);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("Cooldown gate drops restart within 1000ms (REQ-PR-2)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let restartCount = match$1[1];
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, true, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "app.js"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("first restart fires", "=", (a, b) => a === b, restartCount.contents, 1);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "style.css"
  });
  Monitor_socketMjs.advanceTime(800);
  Test.assertion("second restart within cooldown window is dropped", "=", (a, b) => a === b, restartCount.contents, 1);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("BrowserReload does NOT call onReload when enableLiveReload=false (REQ-FW-5)", () => {
  Monitor_socketMjs.makeFakeClock();
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, false, match[0], match$1[0]);
  Monitor._testEmit(handle, {
    TAG: "Modified",
    _0: "index.html"
  });
  Monitor_socketMjs.advanceTime(600);
  Test.assertion("onReload not called when enableLiveReload=false", "=", (a, b) => a === b, match[1].contents, 0);
  Monitor.cancel(handle);
  Monitor_socketMjs.restoreClock();
});

Test.test("Monitor.handle is not directly constructible", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Test.doesNotThrow("handle returned by start is valid", () => Monitor.cancel(handle));
});

Test.test("Multiple Monitor.start calls return independent handles", () => {
  let tmpDir = "tests/unit/_tmp_monitor_test";
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let match$2 = makeReloadCallback();
  let match$3 = makeRestartCallback();
  let h1 = Monitor.start(tmpDir, [], true, false, match[0], match$1[0]);
  let h2 = Monitor.start(tmpDir, [".git"], false, true, match$2[0], match$3[0]);
  Test.doesNotThrow("first handle cancelable", () => Monitor.cancel(h1));
  Test.doesNotThrow("second handle cancelable", () => Monitor.cancel(h2));
});

Test.test("Monitor.start accepts empty ignorePatterns", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Test.doesNotThrow("start with empty ignorePatterns works", () => Monitor.cancel(handle));
});

Test.test("Monitor.start accepts restartOnChange=true", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, true, match[0], match$1[0]);
  Test.doesNotThrow("start with restartOnChange=true works", () => Monitor.cancel(handle));
});

export {
  makeFakeClock,
  advanceTime,
  restoreClock,
  makeReloadCallback,
  makeRestartCallback,
}
/*  Not a pure module */
