// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as IgnoreMatcher from "../../src/Watcher/IgnoreMatcher.res.js";

Test.test("empty patterns match nothing", () => {
  let patterns = [];
  let result = IgnoreMatcher.matchesIgnorePattern("foo.txt", patterns);
  Test.assertion("empty patterns array matches nothing", "=", (a, b) => a === b, result, false);
});

Test.test("exact substring match is case insensitive", () => {
  let patterns = [
    "node_modules",
    ".git"
  ];
  let r1 = IgnoreMatcher.matchesIgnorePattern("node_modules/foo.js", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("NODE_MODULES/foo.js", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern("Node_Modules/foo.js", patterns);
  Test.assertion("node_modules matches lowercase", "=", (a, b) => a === b, r1, true);
  Test.assertion("node_modules matches uppercase", "=", (a, b) => a === b, r2, true);
  Test.assertion("node_modules matches mixed", "=", (a, b) => a === b, r3, true);
});

Test.test("glob prefix pattern matches start of path", () => {
  let patterns = ["deno*"];
  let r1 = IgnoreMatcher.matchesIgnorePattern("deno.json", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("deno.lock", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern("deno.json.lock", patterns);
  let r4 = IgnoreMatcher.matchesIgnorePattern("my-deno.json", patterns);
  Test.assertion("deno.json matches", "=", (a, b) => a === b, r1, true);
  Test.assertion("deno.lock matches", "=", (a, b) => a === b, r2, true);
  Test.assertion("deno.json.lock matches (deno prefix)", "=", (a, b) => a === b, r3, true);
  Test.assertion("my-deno.json does not match (not prefix)", "=", (a, b) => a === b, r4, false);
});

Test.test("glob suffix pattern matches end of path", () => {
  let patterns = [
    "*.js",
    "*.ts"
  ];
  let r1 = IgnoreMatcher.matchesIgnorePattern("foo.js", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("bar.ts", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern("foo.jsx", patterns);
  let r4 = IgnoreMatcher.matchesIgnorePattern("foo.module.js", patterns);
  Test.assertion("foo.js matches", "=", (a, b) => a === b, r1, true);
  Test.assertion("bar.ts matches", "=", (a, b) => a === b, r2, true);
  Test.assertion("foo.jsx does not match (extra suffix)", "=", (a, b) => a === b, r3, false);
  Test.assertion("foo.module.js matches *.js (substring)", "=", (a, b) => a === b, r4, true);
});

Test.test("glob contains pattern matches anywhere", () => {
  let patterns = ["*test*"];
  let r1 = IgnoreMatcher.matchesIgnorePattern("test/file.txt", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("mytest.txt", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern("file.test.js", patterns);
  let r4 = IgnoreMatcher.matchesIgnorePattern("testing.txt", patterns);
  Test.assertion("test/file.txt matches", "=", (a, b) => a === b, r1, true);
  Test.assertion("mytest.txt matches", "=", (a, b) => a === b, r2, true);
  Test.assertion("file.test.js matches", "=", (a, b) => a === b, r3, true);
  Test.assertion("testing.txt matches", "=", (a, b) => a === b, r4, true);
});

Test.test("default ignore patterns from spec", () => {
  let patterns = [
    ".git",
    "node_modules",
    ".DS_Store"
  ];
  let r1 = IgnoreMatcher.matchesIgnorePattern(".git/config", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("node_modules/lodash/index.js", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern(".DS_Store", patterns);
  let r4 = IgnoreMatcher.matchesIgnorePattern("src/app.js", patterns);
  Test.assertion(".git/config is ignored", "=", (a, b) => a === b, r1, true);
  Test.assertion("node_modules/... is ignored", "=", (a, b) => a === b, r2, true);
  Test.assertion(".DS_Store is ignored", "=", (a, b) => a === b, r3, true);
  Test.assertion("src/app.js is not ignored", "=", (a, b) => a === b, r4, false);
});

Test.test("patterns are matched case insensitively", () => {
  let patterns = [
    ".GIT",
    "NODE_MODULES"
  ];
  let r1 = IgnoreMatcher.matchesIgnorePattern(".git/hooks", patterns);
  let r2 = IgnoreMatcher.matchesIgnorePattern("NODE_MODULES/pkg/index.js", patterns);
  let r3 = IgnoreMatcher.matchesIgnorePattern("Node_Modules/pkg/index.js", patterns);
  Test.assertion(".git/hooks matches .GIT pattern", "=", (a, b) => a === b, r1, true);
  Test.assertion("NODE_MODULES matches NODE_MODULES pattern", "=", (a, b) => a === b, r2, true);
  Test.assertion("Node_Modules matches NODE_MODULES pattern", "=", (a, b) => a === b, r3, true);
});

Test.test("non-matching pattern returns false", () => {
  let patterns = [
    ".git",
    "node_modules"
  ];
  let r = IgnoreMatcher.matchesIgnorePattern("src/app.ts", patterns);
  Test.assertion("src/app.ts is not ignored by .git/node_modules", "=", (a, b) => a === b, r, false);
});

/*  Not a pure module */
