// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Timers from "../../src/Node/Timers.res.js";
import * as Monitor from "../../src/Watcher/Monitor.res.js";

function makeReloadCallback() {
  let count = {
    contents: 0
  };
  let fn = () => {
    count.contents = count.contents + 1 | 0;
  };
  return [
    fn,
    count
  ];
}

function makeRestartCallback() {
  let count = {
    contents: 0
  };
  let fn = () => {
    count.contents = count.contents + 1 | 0;
  };
  return [
    fn,
    count
  ];
}

Test.test("Monitor.start returns a handle", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [
    ".git",
    "node_modules"
  ], true, false, match[0], match$1[0]);
  Test.assertion("start returns a handle", "=", (a, b) => a === b, true, true);
  Monitor.cancel(handle);
});

Test.test("Monitor.cancel does not throw on valid handle", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [".git"], true, false, match[0], match$1[0]);
  Test.doesNotThrow("cancel does not throw", () => Monitor.cancel(handle));
});

Test.test("Monitor.cancel is idempotent", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, false, match[0], match$1[0]);
  Monitor.cancel(handle);
  Test.doesNotThrow("second cancel does not throw", () => Monitor.cancel(handle));
});

Test.test("Monitor.start accepts all required labeled args", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [
    ".git",
    "node_modules",
    ".DS_Store"
  ], true, true, match[0], match$1[0]);
  Test.assertion("start accepts all labeled args", "=", (a, b) => a === b, true, true);
  Monitor.cancel(handle);
});

Test.test("BrowserReload action does NOT call onReload when enableLiveReload=false", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], false, false, match[0], match$1[0]);
  let fn = () => {};
  let _t = Timers.setTimeout(fn, 100);
  Timers.clearTimeout(_t);
  Monitor.cancel(handle);
  Test.assertion("onReload not called when enableLiveReload=false", "=", (a, b) => a === b, match[1].contents, 0);
});

Test.test("Monitor.handle is not directly constructible", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Test.doesNotThrow("handle returned by start is valid", () => Monitor.cancel(handle));
});

Test.test("Multiple Monitor.start calls return independent handles", () => {
  let tmpDir = "tests/unit/_tmp_monitor_test";
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let match$2 = makeReloadCallback();
  let match$3 = makeRestartCallback();
  let h1 = Monitor.start(tmpDir, [], true, false, match[0], match$1[0]);
  let h2 = Monitor.start(tmpDir, [".git"], false, true, match$2[0], match$3[0]);
  Test.doesNotThrow("first handle cancelable", () => Monitor.cancel(h1));
  Test.doesNotThrow("second handle cancelable", () => Monitor.cancel(h2));
});

Test.test("Monitor.start accepts empty ignorePatterns", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, false, match[0], match$1[0]);
  Test.doesNotThrow("start with empty ignorePatterns works", () => Monitor.cancel(handle));
});

Test.test("Monitor.start accepts restartOnChange=true", () => {
  let match = makeReloadCallback();
  let match$1 = makeRestartCallback();
  let handle = Monitor.start("tests/unit/_tmp_monitor_test", [], true, true, match[0], match$1[0]);
  Test.doesNotThrow("start with restartOnChange=true works", () => Monitor.cancel(handle));
});

export {
  makeReloadCallback,
  makeRestartCallback,
}
/*  Not a pure module */
