// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "../../src/Node/Fs.res.js";
import * as Test from "rescript-test/src/Test.res.js";
import * as Nodefs from "node:fs";
import * as Nodeos from "node:os";
import * as Nodepath from "node:path";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function withTempDir(f) {
  let prefix = Nodepath.join(Nodeos.tmpdir(), "httpath.fs.test.");
  let tempDir = Nodefs.mkdtempSync(prefix);
  try {
    f(tempDir);
  } catch (_e) {
    try {
      Nodefs.rmdirSync(tempDir);
    } catch (exn) {
      
    }
  }
  try {
    Nodefs.rmdirSync(tempDir);
    return;
  } catch (exn$1) {
    return;
  }
}

function withFile(dir, name, content, f) {
  let path = Nodepath.join(dir, name);
  Fs.writeFileSync(path, content);
  f(path);
  Nodefs.unlinkSync(path);
}

Test.test("Fs.readdirSync returns dirents with name and isDirectory", () => withTempDir(tempDir => {
  let filePath = Nodepath.join(tempDir, "readme.txt");
  let dirPath = Nodepath.join(tempDir, "subdir");
  Fs.writeFileSync(filePath, "hello world");
  Nodefs.mkdirSync(dirPath);
  let entries = Fs.readdirSync(tempDir);
  Test.assertion("readdirSync returns 2 entries", "=", (a, b) => a === b, entries.length, 2);
  let fileEntry = entries.find(entry => entry.name === "readme.txt");
  if (fileEntry !== undefined) {
    Test.assertion("file entry isDirectory is false", "=", (a, b) => a === b, fileEntry.isDirectory, false);
  } else {
    Stdlib_JsError.throwWithMessage("Expected to find readme.txt in readdirSync entries");
  }
  let dirEntry = entries.find(entry => entry.name === "subdir");
  if (dirEntry !== undefined) {
    return Test.assertion("dir entry isDirectory is true", "=", (a, b) => a === b, dirEntry.isDirectory, true);
  } else {
    return Stdlib_JsError.throwWithMessage("Expected to find subdir in readdirSync entries");
  }
}));

Test.test("Fs.readFileSync returns UTF-8 file contents", () => withTempDir(tempDir => withFile(tempDir, "greeting.txt", "Hello, 世界!", param => {
  let content = Fs.readFileSync(Nodepath.join(tempDir, "greeting.txt"), "utf-8");
  Test.assertion("readFileSync returns exact content", "=", (a, b) => a === b, content, "Hello, 世界!");
})));

Test.test("Fs.statSync on a file: isFile=true, isDirectory=false, isSymlink=false", () => withTempDir(tempDir => withFile(tempDir, "notes.txt", "test data", filePath => {
  let stats = Fs.statSync(filePath);
  Test.assertion("isFile is true", "=", (a, b) => a === b, Fs.statIsFile(stats), true);
  Test.assertion("isDirectory is false", "=", (a, b) => a === b, Fs.statIsDirectory(stats), false);
  Test.assertion("isSymlink is false", "=", (a, b) => a === b, Fs.statIsSymlink(stats), false);
})));

Test.test("Fs.statSync on a directory: isDirectory=true, isFile=false", () => withTempDir(tempDir => {
  let subdir = Nodepath.join(tempDir, "mydir");
  Nodefs.mkdirSync(subdir);
  let stats = Fs.statSync(subdir);
  Test.assertion("isDirectory is true", "=", (a, b) => a === b, Fs.statIsDirectory(stats), true);
  Test.assertion("isFile is false", "=", (a, b) => a === b, Fs.statIsFile(stats), false);
}));

Test.test("Fs.lstatSync on a symlink: isSymlink=true (while statSync follows)", () => withTempDir(tempDir => {
  let target = Nodepath.join(tempDir, "target.txt");
  let link = Nodepath.join(tempDir, "link.txt");
  Fs.writeFileSync(target, "target content");
  Nodefs.symlinkSync(target, link);
  let lstats = Fs.lstatSync(link);
  Test.assertion("lstatSync: isSymlink is true", "=", (a, b) => a === b, Fs.statIsSymlink(lstats), true);
  Test.assertion("lstatSync: isFile is false (it's a symlink)", "=", (a, b) => a === b, Fs.statIsFile(lstats), false);
  let stats = Fs.statSync(link);
  Test.assertion("statSync follows: isFile is true", "=", (a, b) => a === b, Fs.statIsFile(stats), true);
  Test.assertion("statSync follows: isSymlink is false", "=", (a, b) => a === b, Fs.statIsSymlink(stats), false);
}));

Test.test("Fs.createReadStream returns a readStream (existing API)", () => withTempDir(tempDir => withFile(tempDir, "stream-test.txt", "stream content", filePath => {
  let rs = Fs.createReadStream(filePath);
  rs.on("error", () => {});
  Test.assertion("createReadStream produces a value", "=", (a, b) => a === b, true, true);
  rs.destroy();
})));

export {
  withTempDir,
  withFile,
}
/*  Not a pure module */
