// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Node_Path from "../../src/Node/Node_Path.res.js";

Test.test("Node_Path.resolve returns absolute path unchanged", () => {
  let abs = Node_Path.resolve("/foo/bar", "");
  let firstCharOpt = abs[0];
  let isAbs = firstCharOpt === "/";
  Test.assertion("resolve(/foo/bar, '') is absolute (starts with /)", "=", (a, b) => a === b, isAbs, true);
});

Test.test("Node_Path.resolve('/a', '/b') returns the last absolute segment", () => {
  let result = Node_Path.resolve("/a", "/b");
  Test.assertion("resolve(/a, /b) is /b", "=", (a, b) => a === b, result, "/b");
});

Test.test("Node_Path.resolve('/foo/bar', '') returns /foo/bar", () => {
  let result = Node_Path.resolve("/foo/bar", "");
  Test.assertion("resolve(/foo/bar, empty) is /foo/bar", "=", (a, b) => a === b, result, "/foo/bar");
});

Test.test("Node_Path.join('a', 'b') returns a/b", () => {
  let result = Node_Path.join("a", "b");
  Test.assertion("join(a, b) is a/b", "=", (a, b) => a === b, result, "a/b");
});

Test.test("Node_Path.join('/a', 'b') returns /a/b", () => {
  let result = Node_Path.join("/a", "b");
  Test.assertion("join(/a, b) is /a/b", "=", (a, b) => a === b, result, "/a/b");
});

Test.test("Node_Path.normalize('a/b/../c') returns a/c", () => {
  let result = Node_Path.normalize("a/b/../c");
  Test.assertion("normalize(a/b/../c) is a/c", "=", (a, b) => a === b, result, "a/c");
});

Test.test("Node_Path.normalize('a/b/./c') returns a/b/c", () => {
  let result = Node_Path.normalize("a/b/./c");
  Test.assertion("normalize(a/b/./c) is a/b/c", "=", (a, b) => a === b, result, "a/b/c");
});

Test.test("Node_Path.normalize('./foo') returns foo", () => {
  let result = Node_Path.normalize("./foo");
  Test.assertion("normalize(./foo) is foo", "=", (a, b) => a === b, result, "foo");
});

Test.test("Node_Path.relative('/a/b', '/a/b/c') returns c", () => {
  let result = Node_Path.relative("/a/b", "/a/b/c");
  Test.assertion("relative(/a/b, /a/b/c) is c", "=", (a, b) => a === b, result, "c");
});

Test.test("Node_Path.relative('/a/b/c', '/a/b') returns ..", () => {
  let result = Node_Path.relative("/a/b/c", "/a/b");
  Test.assertion("relative(/a/b/c, /a/b) is ..", "=", (a, b) => a === b, result, "..");
});

Test.test("Node_Path.extname('file.txt') returns .txt", () => {
  let result = Node_Path.extname("file.txt");
  Test.assertion("extname(file.txt) is .txt", "=", (a, b) => a === b, result, ".txt");
});

Test.test("Node_Path.extname('file') returns empty string", () => {
  let result = Node_Path.extname("file");
  Test.assertion("extname(file) is empty", "=", (a, b) => a === b, result, "");
});

Test.test("Node_Path.extname('file.tar.gz') returns .gz", () => {
  let result = Node_Path.extname("file.tar.gz");
  Test.assertion("extname(file.tar.gz) is .gz", "=", (a, b) => a === b, result, ".gz");
});

Test.test("Node_Path.basename('/foo/bar.txt') returns bar.txt", () => {
  let result = Node_Path.basename("/foo/bar.txt");
  Test.assertion("basename(/foo/bar.txt) is bar.txt", "=", (a, b) => a === b, result, "bar.txt");
});

Test.test("Node_Path.basename('/foo/') returns foo", () => {
  let result = Node_Path.basename("/foo/");
  Test.assertion("basename(/foo/) is foo", "=", (a, b) => a === b, result, "foo");
});

/*  Not a pure module */
