// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Buffer from "../../src/Node/Buffer.res.js";

Test.test("Buffer.length returns correct byte length", () => {
  let buf = Buffer.fromString("hello", "utf8");
  Test.assertion("length of 'hello' is 5", "=", (a, b) => a === b, Buffer.length(buf), 5);
});

Test.test("Buffer.concat of single buffer returns identical bytes", () => {
  let original = Buffer.fromString("hello", "utf8");
  let combined = Buffer.concat([original]);
  let i = 0;
  let pass = true;
  while (i < 5) {
    let expected = Buffer.readUInt8(original, i);
    let actual = Buffer.readUInt8(combined, i);
    if (expected !== actual) {
      pass = false;
    }
    i = i + 1 | 0;
  };
  Test.assertion("concat identity preserves all 5 bytes", "=", (a, b) => a === b, pass, true);
});

Test.test("Buffer.fromString round-trip via readUInt8 recovers correct bytes", () => {
  let buf = Buffer.fromString("reload", "utf8");
  let expected = [
    114,
    101,
    108,
    111,
    97,
    100
  ];
  let i = 0;
  let pass = true;
  while (i < 6) {
    let v = expected[i];
    let exp = v !== undefined ? v : -1;
    let act = Buffer.readUInt8(buf, i);
    if (exp !== act) {
      pass = false;
    }
    i = i + 1 | 0;
  };
  Test.assertion("fromString round-trip via readUInt8 recovers [114,101,108,111,97,100]", "=", (a, b) => a === b, pass, true);
});

/*  Not a pure module */
