// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Events from "../../src/Node/Events.res.js";
import * as Ws_hub_socketMjs from "./ws_hub_socket.mjs";

function createFakeSocket(prim) {
  return Ws_hub_socketMjs.createFakeSocket();
}

function getCounter(prim) {
  return Ws_hub_socketMjs.getCounter();
}

function callListeners(prim0, prim1) {
  Ws_hub_socketMjs.callListeners(prim0, prim1);
}

Test.test("Events.on attaches listener — callListeners verifies it fires", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  let counter = Ws_hub_socketMjs.getCounter();
  counter.count = 0;
  let listener = () => {
    counter.count = counter.count + 1 | 0;
  };
  Events.on(fake, "close", listener);
  Ws_hub_socketMjs.callListeners(fake, "close");
  Test.assertion("listener fired when event emitted — count is 1", "=", (a, b) => a === b, counter.count, 1);
});

Test.test("Events.remove detaches listener — callListeners after remove shows no fire", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  let counter = Ws_hub_socketMjs.getCounter();
  counter.count = 0;
  let listener = () => {
    counter.count = counter.count + 1 | 0;
  };
  Events.on(fake, "close", listener);
  Ws_hub_socketMjs.callListeners(fake, "close");
  Test.assertion("listener fires before removal", "=", (a, b) => a === b, counter.count, 1);
  counter.count = 0;
  Events.remove(fake, "close", listener);
  Ws_hub_socketMjs.callListeners(fake, "close");
  Test.assertion("listener does NOT fire after removal — count stays 0", "=", (a, b) => a === b, counter.count, 0);
});

Test.test("Events.on is fluent — returns socket for chaining", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  let result = Events.on(fake, "data", () => {});
  let chained = Events.remove(result, "data", () => {});
  let called = {
    contents: false
  };
  let listener = () => {
    called.contents = true;
  };
  Events.on(chained, "error", listener);
  Test.assertion("on returns socket; remove returns socket; both accept further on calls", "=", (a, b) => a === b, true, true);
});

export {
  createFakeSocket,
  getCounter,
  callListeners,
}
/*  Not a pure module */
