// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Parser from "../../src/Cfg/Parser.res.js";
import * as ParseError from "../../src/Cfg/ParseError.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function unwrapConfig(r) {
  if (r.TAG === "Ok") {
    return r._0;
  }
  let msg = ParseError.toString(r._0);
  return Stdlib_JsError.throwWithMessage("unwrapConfig called on Error: " + msg);
}

Test.test("parse([]) returns all defaults", () => {
  let result = Parser.parse([]);
  if (result.TAG === "Ok") {
    let c = result._0;
    Test.assertion("hostname is 127.0.0.1", "=", (a, b) => a === b, c.hostname, "127.0.0.1");
    Test.assertion("port is 8080", "=", (a, b) => a === b, c.port, 8080);
    Test.assertion("enableDirectoryListing is false", "=", (a, b) => a === b, c.enableDirectoryListing, false);
    Test.assertion("enableLiveReload is true", "=", (a, b) => a === b, c.enableLiveReload, true);
    Test.assertion("restartOnChange is false", "=", (a, b) => a === b, c.restartOnChange, false);
    Test.assertion("lan is false", "=", (a, b) => a === b, c.lan, false);
    Test.assertion("allowProtectedDir is false", "=", (a, b) => a === b, c.allowProtectedDir, false);
    Test.assertion("logLevel is Info", "=", (a, b) => a === b, c.logLevel, "Info");
    return Test.assertion("ignorePatterns has 3 entries", "=", (a, b) => a === b, c.ignorePatterns.length, 3);
  }
  let msg = ParseError.toString(result._0);
  Stdlib_JsError.throwWithMessage("Expected Ok, got Error: " + msg);
});

Test.test("parse([\"-d\", \"/tmp\", \"-p\", \"3000\"]) sets dir and port", () => {
  let c = unwrapConfig(Parser.parse([
    "-d",
    "/tmp",
    "-p",
    "3000"
  ]));
  Test.assertion("directory is /tmp (resolved)", "=", (a, b) => a === b, c.port, 3000);
  Test.assertion("port is 3000", "=", (a, b) => a === b, c.port, 3000);
});

Test.test("parse([\"--dir\", \"/var/log\", \"--port\", \"9000\"]) long forms", () => {
  let c = unwrapConfig(Parser.parse([
    "--dir",
    "/var/log",
    "--port",
    "9000"
  ]));
  Test.assertion("port is 9000", "=", (a, b) => a === b, c.port, 9000);
});

Test.test("--listing sets enableDirectoryListing to true", () => {
  let c = unwrapConfig(Parser.parse(["--listing"]));
  Test.assertion("enableDirectoryListing is true with --listing", "=", (a, b) => a === b, c.enableDirectoryListing, true);
});

Test.test("--no-listing sets enableDirectoryListing to false", () => {
  let c = unwrapConfig(Parser.parse(["--no-listing"]));
  Test.assertion("enableDirectoryListing is false with --no-listing", "=", (a, b) => a === b, c.enableDirectoryListing, false);
});

Test.test("--listing --no-listing: no-listing wins (listing && !no-listing)", () => {
  let c = unwrapConfig(Parser.parse([
    "--listing",
    "--no-listing"
  ]));
  Test.assertion("enableDirectoryListing is false when both present", "=", (a, b) => a === b, c.enableDirectoryListing, false);
});

Test.test("--host overrides default", () => {
  let c = unwrapConfig(Parser.parse([
    "--host",
    "0.0.0.0"
  ]));
  Test.assertion("hostname is explicitly set", "=", (a, b) => a === b, c.hostname, "0.0.0.0");
});

Test.test("--lan sets hostname to 0.0.0.0", () => {
  let c = unwrapConfig(Parser.parse(["--lan"]));
  Test.assertion("hostname is 0.0.0.0 with --lan", "=", (a, b) => a === b, c.hostname, "0.0.0.0");
});

Test.test("-l (alias) sets hostname to 0.0.0.0", () => {
  let c = unwrapConfig(Parser.parse(["-l"]));
  Test.assertion("hostname is 0.0.0.0 with -l", "=", (a, b) => a === b, c.hostname, "0.0.0.0");
});

Test.test("--host overrides --lan (explicit host wins)", () => {
  let c = unwrapConfig(Parser.parse([
    "--host",
    "192.168.1.1",
    "--lan"
  ]));
  Test.assertion("explicit --host wins over --lan", "=", (a, b) => a === b, c.hostname, "192.168.1.1");
});

Test.test("-r sets restartOnChange to true", () => {
  let c = unwrapConfig(Parser.parse(["-r"]));
  Test.assertion("restartOnChange is true with -r", "=", (a, b) => a === b, c.restartOnChange, true);
});

Test.test("--restart-on-change sets restartOnChange to true", () => {
  let c = unwrapConfig(Parser.parse(["--restart-on-change"]));
  Test.assertion("restartOnChange is true with --restart-on-change", "=", (a, b) => a === b, c.restartOnChange, true);
});

Test.test("--no-live-reload sets enableLiveReload to false", () => {
  let c = unwrapConfig(Parser.parse(["--no-live-reload"]));
  Test.assertion("enableLiveReload is false with --no-live-reload", "=", (a, b) => a === b, c.enableLiveReload, false);
});

Test.test("port 0 is valid (ephemeral)", () => {
  let c = unwrapConfig(Parser.parse([
    "--port",
    "0"
  ]));
  Test.assertion("port 0 is valid", "=", (a, b) => a === b, c.port, 0);
});

Test.test("port 65535 is valid", () => {
  let c = unwrapConfig(Parser.parse([
    "--port",
    "65535"
  ]));
  Test.assertion("port 65535 is valid", "=", (a, b) => a === b, c.port, 65535);
});

Test.test("port 65536 is invalid", () => {
  let r = Parser.parse([
    "--port",
    "65536"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("65536 should be Error", "=", (a, b) => a === b, false, true);
  }
  let p = r._0;
  if (typeof p === "object" && p.TAG === "InvalidPort") {
    return Test.assertion("InvalidPort error returned", "=", (a, b) => a === b, p._0, 65536);
  }
  let msg = ParseError.toString(p);
  Stdlib_JsError.throwWithMessage("Expected InvalidPort, got: " + msg);
});

Test.test("negative port is invalid", () => {
  let r = Parser.parse([
    "--port",
    "-1"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("-1 should be Error", "=", (a, b) => a === b, false, true);
  }
  let e = r._0;
  if (typeof e === "object" && e.TAG === "InvalidPort") {
    return Test.assertion("InvalidPort error returned for -1", "=", (a, b) => a === b, true, true);
  }
  let msg = ParseError.toString(e);
  Stdlib_JsError.throwWithMessage("Expected InvalidPort, got: " + msg);
});

Test.test("non-numeric port is invalid", () => {
  let r = Parser.parse([
    "--port",
    "abc"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("abc should be Error", "=", (a, b) => a === b, false, true);
  }
  let e = r._0;
  if (typeof e === "object" && e.TAG === "InvalidPort" && e._0 === 0) {
    return Test.assertion("InvalidPort(0) returned for non-numeric", "=", (a, b) => a === b, true, true);
  }
  let msg = ParseError.toString(e);
  Stdlib_JsError.throwWithMessage("Expected InvalidPort, got: " + msg);
});

Test.test("--log info returns Info", () => {
  let c = unwrapConfig(Parser.parse([
    "--log",
    "info"
  ]));
  Test.assertion("logLevel is Info", "=", (a, b) => a === b, c.logLevel, "Info");
});

Test.test("--log debug returns Debug", () => {
  let c = unwrapConfig(Parser.parse([
    "--log",
    "debug"
  ]));
  Test.assertion("logLevel is Debug", "=", (a, b) => a === b, c.logLevel, "Debug");
});

Test.test("--log error returns Error", () => {
  let c = unwrapConfig(Parser.parse([
    "--log",
    "error"
  ]));
  Test.assertion("logLevel is Error", "=", (a, b) => a === b, c.logLevel, "Error");
});

Test.test("--log trace returns InvalidLogLevel error", () => {
  let r = Parser.parse([
    "--log",
    "trace"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("trace should be Error", "=", (a, b) => a === b, false, true);
  }
  let s = r._0;
  if (typeof s === "object" && s.TAG === "InvalidLogLevel") {
    return Test.assertion("InvalidLogLevel(\"trace\")", "=", (a, b) => a === b, s._0, "trace");
  }
  let msg = ParseError.toString(s);
  Stdlib_JsError.throwWithMessage("Expected InvalidLogLevel, got: " + msg);
});

Test.test("--dir with no value returns MissingValue", () => {
  let r = Parser.parse(["--dir"]);
  if (r.TAG === "Ok") {
    return Test.assertion("--dir alone should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "MissingValue") {
    return Test.assertion("MissingValue for --dir", "=", (a, b) => a === b, flag._0, "--dir");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected MissingValue, got: " + msg);
});

Test.test("--port with no value returns MissingValue", () => {
  let r = Parser.parse(["--port"]);
  if (r.TAG === "Ok") {
    return Test.assertion("--port alone should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "MissingValue") {
    return Test.assertion("MissingValue for --port", "=", (a, b) => a === b, flag._0, "--port");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected MissingValue, got: " + msg);
});

Test.test("unknown flag returns UnknownFlag", () => {
  let r = Parser.parse(["--unknown-flag"]);
  if (r.TAG === "Ok") {
    return Test.assertion("--unknown-flag should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "UnknownFlag") {
    return Test.assertion("UnknownFlag for --unknown-flag", "=", (a, b) => a === b, flag._0, "--unknown-flag");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected UnknownFlag, got: " + msg);
});

Test.test("unknown short flag -z returns UnknownFlag", () => {
  let r = Parser.parse(["-z"]);
  if (r.TAG === "Ok") {
    return Test.assertion("-z should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "UnknownFlag") {
    return Test.assertion("UnknownFlag for -z", "=", (a, b) => a === b, flag._0, "-z");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected UnknownFlag, got: " + msg);
});

Test.test("--trust-proxy returns RemovedFlag error", () => {
  let r = Parser.parse(["--trust-proxy"]);
  if (r.TAG === "Ok") {
    return Test.assertion("--trust-proxy should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "RemovedFlag") {
    return Test.assertion("RemovedFlag for --trust-proxy", "=", (a, b) => a === b, flag._0, "--trust-proxy");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected RemovedFlag, got: " + msg);
});

Test.test("--rate-limit-max-requests returns RemovedFlag error", () => {
  let r = Parser.parse([
    "--rate-limit-max-requests",
    "10"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("--rate-limit-max-requests should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "RemovedFlag") {
    return Test.assertion("RemovedFlag for --rate-limit-max-requests", "=", (a, b) => a === b, flag._0, "--rate-limit-max-requests");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected RemovedFlag, got: " + msg);
});

Test.test("--rate-limit-window-ms returns RemovedFlag error", () => {
  let r = Parser.parse([
    "--rate-limit-window-ms",
    "60000"
  ]);
  if (r.TAG === "Ok") {
    return Test.assertion("--rate-limit-window-ms should be Error", "=", (a, b) => a === b, false, true);
  }
  let flag = r._0;
  if (typeof flag === "object" && flag.TAG === "RemovedFlag") {
    return Test.assertion("RemovedFlag for --rate-limit-window-ms", "=", (a, b) => a === b, flag._0, "--rate-limit-window-ms");
  }
  let msg = ParseError.toString(flag);
  Stdlib_JsError.throwWithMessage("Expected RemovedFlag, got: " + msg);
});

Test.test("--help returns HelpRequested error", () => {
  let r = Parser.parse(["--help"]);
  if (r.TAG === "Ok") {
    return Test.assertion("--help should return HelpRequested", "=", (a, b) => a === b, false, true);
  }
  let e = r._0;
  if (typeof e !== "object") {
    return Test.assertion("HelpRequested returned for --help", "=", (a, b) => a === b, true, true);
  }
  let msg = ParseError.toString(e);
  Stdlib_JsError.throwWithMessage("Expected HelpRequested, got: " + msg);
});

Test.test("-h returns HelpRequested error", () => {
  let r = Parser.parse(["-h"]);
  if (r.TAG === "Ok") {
    return Test.assertion("-h should return HelpRequested", "=", (a, b) => a === b, false, true);
  }
  let e = r._0;
  if (typeof e !== "object") {
    return Test.assertion("HelpRequested returned for -h", "=", (a, b) => a === b, true, true);
  }
  let msg = ParseError.toString(e);
  Stdlib_JsError.throwWithMessage("Expected HelpRequested, got: " + msg);
});

Test.test("--ignore with single pattern", () => {
  let c = unwrapConfig(Parser.parse([
    "--ignore",
    "*.log"
  ]));
  Test.assertion("ignorePatterns has 1 entry", "=", (a, b) => a === b, c.ignorePatterns.length, 1);
  Test.assertion("first pattern is *.log", "=", (a, b) => a === b, Stdlib_Option.getOr(c.ignorePatterns[0], ""), "*.log");
});

Test.test("--ignore with comma-separated patterns", () => {
  let c = unwrapConfig(Parser.parse([
    "--ignore",
    "*.log,temp/,*.tmp"
  ]));
  Test.assertion("ignorePatterns has 3 entries", "=", (a, b) => a === b, c.ignorePatterns.length, 3);
});

Test.test("-i with patterns", () => {
  let c = unwrapConfig(Parser.parse([
    "-i",
    "*.bak"
  ]));
  Test.assertion("ignorePatterns has 1 entry via -i", "=", (a, b) => a === b, c.ignorePatterns.length, 1);
});

Test.test("parse is deterministic (same args => same config)", () => {
  let args = [
    "--dir",
    "/tmp",
    "-p",
    "3000",
    "--lan"
  ];
  let r1 = Parser.parse(args);
  let r2 = Parser.parse(args);
  if (r1.TAG !== "Ok") {
    return Stdlib_JsError.throwWithMessage("Both results should be Ok for deterministic test");
  }
  let c1 = r1._0;
  if (r2.TAG !== "Ok") {
    return Stdlib_JsError.throwWithMessage("Both results should be Ok for deterministic test");
  }
  let c2 = r2._0;
  Test.assertion("same args produce same port", "=", (a, b) => a === b, c1.port, c2.port);
  Test.assertion("same args produce same hostname", "=", (a, b) => a === b, c1.hostname, c2.hostname);
});

Test.test("--allow-protected-dir sets allowProtectedDir to true", () => {
  let c = unwrapConfig(Parser.parse(["--allow-protected-dir"]));
  Test.assertion("allowProtectedDir is true", "=", (a, b) => a === b, c.allowProtectedDir, true);
});

Test.test("non-flag arguments are skipped", () => {
  let c = unwrapConfig(Parser.parse([
    "some-file.txt",
    "--port",
    "4000",
    "another.html"
  ]));
  Test.assertion("port is parsed despite non-flag args", "=", (a, b) => a === b, c.port, 4000);
});

export {
  unwrapConfig,
}
/*  Not a pure module */
