// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as ParseError from "../../src/Cli/ParseError.res.js";

Test.test("UnknownFlag.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "UnknownFlag",
    _0: "--foo"
  });
  Test.assertion("toString returns Unknown flag format", "=", (a, b) => a === b, s, "Unknown flag: --foo");
});

Test.test("MissingValue.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "MissingValue",
    _0: "-d"
  });
  Test.assertion("toString returns Missing value format", "=", (a, b) => a === b, s, "Missing value for flag: -d");
});

Test.test("InvalidPort.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "InvalidPort",
    _0: 99999
  });
  Test.assertion("toString returns Invalid port format with port number", "=", (a, b) => a === b, s, "Invalid port: 99999. Must be between 0 and 65535.");
});

Test.test("InvalidPort.toString works for negative port", () => {
  let s = ParseError.toString({
    TAG: "InvalidPort",
    _0: -1
  });
  Test.assertion("toString handles negative port", "=", (a, b) => a === b, s.includes("Invalid port"), true);
});

Test.test("InvalidLogLevel.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "InvalidLogLevel",
    _0: "trace"
  });
  Test.assertion("toString returns Invalid log level format", "=", (a, b) => a === b, s, "Invalid log level: trace. Must be one of: info, debug, error.");
});

Test.test("RemovedFlag.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "RemovedFlag",
    _0: "--trust-proxy"
  });
  Test.assertion("toString returns Removed flag format", "=", (a, b) => a === b, s, "Flag has been removed: --trust-proxy");
});

Test.test("InvalidPath.toString formats correctly", () => {
  let s = ParseError.toString({
    TAG: "InvalidPath",
    _0: "/nonexistent/dir"
  });
  Test.assertion("toString returns Invalid path format", "=", (a, b) => a === b, s, "Invalid path: /nonexistent/dir");
});

Test.test("HelpRequested.toString returns Help requested", () => {
  let s = ParseError.toString("HelpRequested");
  Test.assertion("toString returns 'Help requested'", "=", (a, b) => a === b, s, "Help requested");
});

Test.test("each variant produces a distinct string", () => {
  let s1 = ParseError.toString({
    TAG: "UnknownFlag",
    _0: "x"
  });
  let s2 = ParseError.toString({
    TAG: "MissingValue",
    _0: "x"
  });
  let s3 = ParseError.toString({
    TAG: "InvalidPort",
    _0: 0
  });
  let s4 = ParseError.toString({
    TAG: "InvalidLogLevel",
    _0: "x"
  });
  let s5 = ParseError.toString({
    TAG: "RemovedFlag",
    _0: "x"
  });
  let s6 = ParseError.toString({
    TAG: "InvalidPath",
    _0: "x"
  });
  let s7 = ParseError.toString("HelpRequested");
  let allDistinct = s1 !== s2 && s1 !== s3 && s1 !== s4 && s1 !== s5 && s1 !== s6 && s1 !== s7 && s2 !== s3 && s2 !== s4 && s2 !== s5 && s2 !== s6 && s2 !== s7 && s3 !== s4 && s3 !== s5 && s3 !== s6 && s3 !== s7 && s4 !== s5 && s4 !== s6 && s4 !== s7 && s5 !== s6 && s5 !== s7 && s6 !== s7;
  Test.assertion("all 7 variants produce distinct strings", "=", (a, b) => a === b, allDistinct, true);
});

/*  Not a pure module */
