// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "../../src/Utils/Path.res.js";
import * as Test from "rescript-test/src/Test.res.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

Test.test("resolveSafePath: safe relative path returns resolved absolute", () => {
  let result = Path.resolveSafePath("/srv", "./files/index.html");
  if (result !== undefined) {
    return Test.assertion("resolved path starts with base", "=", (a, b) => a === b, result.startsWith("/srv"), true);
  } else {
    return Stdlib_JsError.throwWithMessage("Expected Some but got None for safe path");
  }
});

Test.test("resolveSafePath: traversal attempt returns None", () => {
  let result = Path.resolveSafePath("/srv", "../../../etc/passwd");
  Test.assertion("traversal returns None", "=", Primitive_object.equal, result, undefined);
});

Test.test("resolveSafePath: absolute path /etc alongside /srv returns Some (not traversal)", () => {
  let result = Path.resolveSafePath("/srv", "/etc/passwd");
  if (result !== undefined) {
    return Test.assertion("/etc/passwd resolves to /srv/etc/passwd (alongside, not above)", "=", (a, b) => a === b, result, "/srv/etc/passwd");
  } else {
    return Stdlib_JsError.throwWithMessage("Expected Some for /etc/passwd alongside /srv");
  }
});

Test.test("resolveSafePath: exact base match returns Some(base)", () => {
  let result = Path.resolveSafePath("/srv", ".");
  if (result !== undefined) {
    return Test.assertion("requested '.' resolves to base", "=", (a, b) => a === b, result, "/srv");
  } else {
    return Stdlib_JsError.throwWithMessage("Expected Some for exact base match");
  }
});

Test.test("matchesPattern: path containing node_modules matches 'node_modules'", () => {
  let result = Path.matchesPattern("src/node_modules/foo/bar.js", ["node_modules"]);
  Test.assertion("node_modules pattern matches in path", "=", (a, b) => a === b, result, true);
});

Test.test("matchesPattern: path without node_modules does not match", () => {
  let result = Path.matchesPattern("src/app/main.js", ["node_modules"]);
  Test.assertion("app/main.js does not match node_modules", "=", (a, b) => a === b, result, false);
});

Test.test("matchesPattern: pattern longer than path does not match", () => {
  let result = Path.matchesPattern("a/b", ["a/b/c"]);
  Test.assertion("pattern longer than path returns false", "=", (a, b) => a === b, result, false);
});

Test.test("matchesPattern: exact segment match works", () => {
  let result = Path.matchesPattern("src/config/settings.json", ["config"]);
  Test.assertion("config pattern matches src/config/settings.json", "=", (a, b) => a === b, result, true);
});

Test.test("matchesPattern: empty pattern returns false", () => {
  let result = Path.matchesPattern("src/app/main.js", [""]);
  Test.assertion("empty pattern returns false", "=", (a, b) => a === b, result, false);
});

Test.test("matchesPattern: backslash separator is normalized to forward slash", () => {
  let result = Path.matchesPattern("src\\node_modules\\foo.js", ["node_modules"]);
  Test.assertion("backslash path normalized to forward slash for matching", "=", (a, b) => a === b, result, true);
});

/*  Not a pure module */
