// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Process from "../../src/Node/Process.res.js";
import * as Process_fakeMjs from "./process_fake.mjs";

function _getLastExitCode(prim) {
  return Process_fakeMjs.getLastExitCode();
}

function _resetExitCode(prim) {
  Process_fakeMjs.resetExitCode();
}

Test.test("Process.exit(0) records exit code 0 without terminating", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(0);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(0) records code 0", "=", (a, b) => a === b, code, 0);
});

Test.test("Process.exit(1) records exit code 1 without terminating", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(1);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(1) records code 1", "=", (a, b) => a === b, code, 1);
});

Test.test("Process.exit(42) records exit code 42", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(42);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(42) records code 42", "=", (a, b) => a === b, code, 42);
});

Test.test("Process.argv is an array with at least 2 elements", () => {
  let len = Process.argv.length;
  Test.assertion("argv has at least 2 elements (node + script)", ">=", (a, b) => a >= b, len, 2);
});

Test.test("Process.argv[0] is the node executable path", () => {
  let p = Process.argv[0];
  let nodePath = p !== undefined ? p : "";
  Test.assertion("argv[0] is non-empty string", "=", (a, b) => a === b, nodePath !== "", true);
});

Test.test("Process.argv[1] is the script path", () => {
  let p = Process.argv[1];
  let scriptPath = p !== undefined ? p : "";
  Test.assertion("argv[1] is non-empty string", "=", (a, b) => a === b, scriptPath !== "", true);
});

export {
  _getLastExitCode,
  _resetExitCode,
}
/*  Not a pure module */
