// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Process from "../../src/Node/Process.res.js";
import * as Process_fakeMjs from "./process_fake.mjs";

function _getLastExitCode(prim) {
  return Process_fakeMjs.getLastExitCode();
}

function _resetExitCode(prim) {
  Process_fakeMjs.resetExitCode();
}

Test.test("Process.exit(0) records exit code 0 without terminating", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(0);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(0) records code 0", "=", (a, b) => a === b, code, 0);
});

Test.test("Process.exit(1) records exit code 1 without terminating", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(1);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(1) records code 1", "=", (a, b) => a === b, code, 1);
});

Test.test("Process.exit(42) records exit code 42", () => {
  Process_fakeMjs.resetExitCode();
  Process.exit(42);
  let code = Process_fakeMjs.getLastExitCode();
  Test.assertion("exit(42) records code 42", "=", (a, b) => a === b, code, 42);
});

export {
  _getLastExitCode,
  _resetExitCode,
}
/*  Not a pure module */
