// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Templates from "../../src/Ui/Templates.res.js";

Test.test("Templates.escapeHtml: ampersand becomes &amp;", () => {
  let result = Templates.escapeHtml("a & b");
  Test.assertion("ampersand escaped", "=", (a, b) => a === b, result, "a &amp; b");
});

Test.test("Templates.escapeHtml: less-than becomes &lt;", () => {
  let result = Templates.escapeHtml("<script>");
  Test.assertion("< escaped", "=", (a, b) => a === b, result, "&lt;script&gt;");
});

Test.test("Templates.escapeHtml: greater-than becomes &gt;", () => {
  let result = Templates.escapeHtml("a > b");
  Test.assertion("> escaped", "=", (a, b) => a === b, result, "a &gt; b");
});

Test.test("Templates.escapeHtml: double-quote becomes &quot;", () => {
  let result = Templates.escapeHtml("say \"hello\"");
  Test.assertion("double-quote escaped", "=", (a, b) => a === b, result, "say &quot;hello&quot;");
});

Test.test("Templates.escapeHtml: single-quote (straight apostrophe) becomes &#39;", () => {
  let input = "it's";
  let result = Templates.escapeHtml(input);
  Test.assertion("apostrophe escaped", "=", (a, b) => a === b, result, "it&#39;s");
});

Test.test("Templates.escapeHtml: mixed XSS payload", () => {
  let result = Templates.escapeHtml("<script>alert('XSS')</script>");
  Test.assertion("full XSS escaped", "=", (a, b) => a === b, result, "&lt;script&gt;alert(&#39;XSS&#39;)&lt;/script&gt;");
});

Test.test("Templates.escapeHtml: empty string is unchanged", () => {
  let result = Templates.escapeHtml("");
  Test.assertion("empty stays empty", "=", (a, b) => a === b, result, "");
});

Test.test("Templates.escapeHtml: plain text is unchanged", () => {
  let result = Templates.escapeHtml("hello world 123");
  Test.assertion("plain text unchanged", "=", (a, b) => a === b, result, "hello world 123");
});

Test.test("Templates.fileEntry: can construct with name, isDirectory, url", () => {
  Test.assertion("name field", "=", (a, b) => a === b, "example.txt", "example.txt");
  Test.assertion("isDirectory false", "=", (a, b) => a === b, false, false);
  Test.assertion("url field", "=", (a, b) => a === b, "/example.txt", "/example.txt");
});

Test.test("renderDirectoryListing: non-root shows parent link", () => {
  let entries = [];
  let html = Templates.renderDirectoryListing(entries, "/subdir");
  Test.assertion("contains .. link", "=", (a, b) => a === b, html.includes("href=\"../\""), true);
});

Test.test("renderDirectoryListing: root hides parent link", () => {
  let entries = [];
  let html = Templates.renderDirectoryListing(entries, "/");
  Test.assertion("root has no parent link", "=", (a, b) => a === b, html.includes("href=\"../\""), false);
});

Test.test("renderDirectoryListing: empty directory shows empty state", () => {
  let entries = [];
  let html = Templates.renderDirectoryListing(entries, "/empty");
  Test.assertion("contains empty state text", "=", (a, b) => a === b, html.includes("This directory is empty"), true);
});

Test.test("renderDirectoryListing: directory emoji for folders", () => {
  let entries = [{
      name: "mydir",
      isDirectory: true,
      url: "/mydir"
    }];
  let html = Templates.renderDirectoryListing(entries, "/");
  Test.assertion("contains folder emoji", "=", (a, b) => a === b, html.includes("📁"), true);
});

Test.test("renderDirectoryListing: file emoji for files", () => {
  let entries = [{
      name: "readme.txt",
      isDirectory: false,
      url: "/readme.txt"
    }];
  let html = Templates.renderDirectoryListing(entries, "/");
  Test.assertion("contains file emoji", "=", (a, b) => a === b, html.includes("📄"), true);
});

Test.test("renderDirectoryListing: directories sorted before files", () => {
  let entries = [
    {
      name: "zebra.txt",
      isDirectory: false,
      url: "/zebra.txt"
    },
    {
      name: "alpha",
      isDirectory: true,
      url: "/alpha"
    },
    {
      name: "beta.txt",
      isDirectory: false,
      url: "/beta.txt"
    },
    {
      name: "gamma",
      isDirectory: true,
      url: "/gamma"
    }
  ];
  let html = Templates.renderDirectoryListing(entries, "/");
  let gammaPos = html.indexOf("<a href=\"/gamma\" class=\"file-item\">");
  let alphaPos = html.indexOf("<a href=\"/alpha\" class=\"file-item\">");
  let betaPos = html.indexOf("<a href=\"/beta.txt\" class=\"file-item\">");
  Test.assertion("gamma before beta", "=", (a, b) => a < b, gammaPos, betaPos);
  Test.assertion("alpha before beta", "=", (a, b) => a < b, alphaPos, betaPos);
});

Test.test("renderDirectoryListing: alpha sorting within same type", () => {
  let entries = [
    {
      name: "zebra.txt",
      isDirectory: false,
      url: "/zebra.txt"
    },
    {
      name: "alpha.txt",
      isDirectory: false,
      url: "/alpha.txt"
    },
    {
      name: "beta.txt",
      isDirectory: false,
      url: "/beta.txt"
    }
  ];
  let html = Templates.renderDirectoryListing(entries, "/");
  let alphaPos = html.indexOf("<a href=\"/alpha.txt\" class=\"file-item\">");
  let betaPos = html.indexOf("<a href=\"/beta.txt\" class=\"file-item\">");
  let zebraPos = html.indexOf("<a href=\"/zebra.txt\" class=\"file-item\">");
  Test.assertion("alpha before beta", "=", (a, b) => a < b, alphaPos, betaPos);
  Test.assertion("beta before zebra", "=", (a, b) => a < b, betaPos, zebraPos);
});

Test.test("renderDirectoryListing: title contains Index of", () => {
  let entries = [];
  let html = Templates.renderDirectoryListing(entries, "/documents");
  Test.assertion("title has Index of", "=", (a, b) => a === b, html.includes("<title>Index of /documents</title>"), true);
});

Test.test("renderDirectoryListing: urlPath is escaped in title", () => {
  let entries = [];
  let html = Templates.renderDirectoryListing(entries, "/<script>");
  Test.assertion("script tag escaped in title", "=", (a, b) => a === b, html.includes("&lt;script&gt;"), true);
});

Test.test("renderDirectoryListing: file names are escaped", () => {
  let entries = [{
      name: "<test>.txt",
      isDirectory: false,
      url: "/<test>.txt"
    }];
  let html = Templates.renderDirectoryListing(entries, "/");
  Test.assertion("filename escaped", "=", (a, b) => a === b, html.includes("&lt;test&gt;"), true);
});

Test.test("renderDirectoryListing: non-root URL is used as href", () => {
  let entries = [{
      name: "my file.txt",
      isDirectory: false,
      url: "/dir/my%20file.txt"
    }];
  let html = Templates.renderDirectoryListing(entries, "/dir");
  Test.assertion("href contains url", "=", (a, b) => a === b, html.includes("href=\"/dir/my%20file.txt\""), true);
});

/*  Not a pure module */
