// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Timers from "../../src/Node/Timers.res.js";

Test.test("Timers.setTimeout returns a timeoutId (opaque type)", () => {
  let fn = () => {};
  Timers.setTimeout(fn, 100);
  Test.assertion("setTimeout returns a value (non-null)", "=", (a, b) => a === b, true, true);
});

Test.test("Timers.clearTimeout does not throw on valid timeoutId", () => {
  let fn = () => {};
  let id = Timers.setTimeout(fn, 1000);
  Test.doesNotThrow("clearTimeout on a valid timeoutId does not throw", () => Timers.clearTimeout(id));
});

Test.test("Timers.setTimeout accepts callback and delay", () => {
  let fn = () => {};
  Timers.setTimeout(fn, 0);
  Timers.setTimeout(fn, 100);
  Timers.setTimeout(fn, 5000);
  Test.assertion("setTimeout accepts various delays without throwing", "=", (a, b) => a === b, true, true);
});

Test.test("Timers.clearTimeout on already-fired id does not throw", () => {
  let fn = () => {};
  let id = Timers.setTimeout(fn, 1);
  Timers.setTimeout(() => {}, 10);
  Test.doesNotThrow("clearTimeout on an already-fired timeoutId does not throw", () => Timers.clearTimeout(id));
});

/*  Not a pure module */
