// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Types from "../../src/Types.res.js";

Test.test("Types.liveReloadEndpoint equals '/livereload'", () => Test.assertion("liveReloadEndpoint", "=", (a, b) => a === b, Types.liveReloadEndpoint, "/livereload"));

Test.test("Types.liveReloadMessage equals 'reload'", () => Test.assertion("liveReloadMessage", "=", (a, b) => a === b, Types.liveReloadMessage, "reload"));

/*  Not a pure module */
