// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as WsHub from "../../src/Hub/WsHub.res.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Ws_hub_socketMjs from "./ws_hub_socket.mjs";

function createFakeSocket(prim) {
  return Ws_hub_socketMjs.createFakeSocket();
}

function getCounter(prim) {
  return Ws_hub_socketMjs.getCounter();
}

function callListeners(prim0, prim1) {
  Ws_hub_socketMjs.callListeners(prim0, prim1);
}

function setThrowMode(prim0, prim1) {
  Ws_hub_socketMjs.setThrowMode(prim0, prim1);
}

function setRejectMode(prim0, prim1) {
  Ws_hub_socketMjs.setRejectMode(prim0, prim1);
}

function getWriteCount(prim) {
  return Ws_hub_socketMjs.getWriteCount(prim);
}

function getLastWrite(prim) {
  return Ws_hub_socketMjs.getLastWrite(prim);
}

function clearWrites(prim) {
  Ws_hub_socketMjs.clearWrites(prim);
}

Test.test("WsHub.register does not throw for a new socket", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake);
  Test.assertion("register new socket should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.register is idempotent — second call is a no-op", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake);
  WsHub.register(fake);
  Test.assertion("double register should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.unregister does not throw for a registered socket", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake);
  WsHub.unregister(fake);
  Test.assertion("unregister registered socket should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.unregister is idempotent — unknown socket is a no-op", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  WsHub.unregister(fake);
  Test.assertion("unregister unknown socket should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.register attaches close listener — socket close triggers unregister", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  let counter = Ws_hub_socketMjs.getCounter();
  counter.count = 0;
  WsHub.register(fake);
  Ws_hub_socketMjs.callListeners(fake, "close");
  let countBefore = counter.count;
  Ws_hub_socketMjs.callListeners(fake, "close");
  let countAfter = counter.count;
  Test.assertion("close event should fire listener once then be removed", "=", Primitive_object.equal, countAfter, countBefore);
});

Test.test("WsHub.register attaches error listener — socket error triggers unregister", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  let counter = Ws_hub_socketMjs.getCounter();
  counter.count = 0;
  WsHub.register(fake);
  Ws_hub_socketMjs.callListeners(fake, "error");
  let countBefore = counter.count;
  Ws_hub_socketMjs.callListeners(fake, "error");
  let countAfter = counter.count;
  Test.assertion("error event should fire listener once then be removed", "=", Primitive_object.equal, countAfter, countBefore);
});

Test.test("WsHub.notifyReload on empty hub is a no-op", () => {
  WsHub.notifyReload();
  Test.assertion("notifyReload on empty hub should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.notifyReload writes to registered socket without throwing", () => {
  let fake = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake);
  WsHub.notifyReload();
  Test.assertion("notifyReload with one client should not throw", "=", (a, b) => a === b, true, true);
});

Test.test("WsHub.notifyReload broadcasts to all registered clients", () => {
  let fake1 = Ws_hub_socketMjs.createFakeSocket();
  let fake2 = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake1);
  WsHub.register(fake2);
  WsHub.notifyReload();
  let wc1 = Ws_hub_socketMjs.getWriteCount(fake1);
  let wc2 = Ws_hub_socketMjs.getWriteCount(fake2);
  Test.assertion("first socket received one write", "=", (a, b) => a === b, wc1, 1);
  Test.assertion("second socket received one write", "=", (a, b) => a === b, wc2, 1);
});

Test.test("WsHub.notifyReload broadcasts in registration order", () => {
  let fake1 = Ws_hub_socketMjs.createFakeSocket();
  let fake2 = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake1);
  WsHub.register(fake2);
  Ws_hub_socketMjs.clearWrites(fake1);
  Ws_hub_socketMjs.clearWrites(fake2);
  WsHub.notifyReload();
  let wc1 = Ws_hub_socketMjs.getWriteCount(fake1);
  let wc2 = Ws_hub_socketMjs.getWriteCount(fake2);
  Test.assertion("writes arrive in insertion order: first registered, first written", "=", (a, b) => a === b, wc1, 1);
  Test.assertion("second registered socket also receives write", "=", (a, b) => a === b, wc2, 1);
});

Test.test("WsHub.notifyReload continues to remaining clients after sync throw", () => {
  let fake1 = Ws_hub_socketMjs.createFakeSocket();
  let fake2 = Ws_hub_socketMjs.createFakeSocket();
  WsHub.register(fake1);
  WsHub.register(fake2);
  Ws_hub_socketMjs.clearWrites(fake1);
  Ws_hub_socketMjs.clearWrites(fake2);
  Ws_hub_socketMjs.setThrowMode(fake1, true);
  WsHub.notifyReload();
  let wc1 = Ws_hub_socketMjs.getWriteCount(fake1);
  let wc2 = Ws_hub_socketMjs.getWriteCount(fake2);
  Test.assertion("dead client was pruned (no write recorded)", "=", (a, b) => a === b, wc1, 0);
  Test.assertion("healthy client still received the write", "=", (a, b) => a === b, wc2, 1);
});

export {
  createFakeSocket,
  getCounter,
  callListeners,
  setThrowMode,
  setRejectMode,
  getWriteCount,
  getLastWrite,
  clearWrites,
}
/*  Not a pure module */
