// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as WsHandshake from "../../src/Http/WsHandshake.res.js";

Test.test("WsHandshake.computeAccept matches RFC 6455 §1.3 test vector", () => Test.assertion("computeAccept matches RFC 6455 §1.3 example", "=", (a, b) => a === b, WsHandshake.computeAccept("dGhlIHNhbXBsZSBub25jZQ=="), "s3pPLMBiTxaQ9kYGzzhZRbK+xOo="));

Test.test("WsHandshake.handshakeResponse starts with HTTP/1.1 101", () => {
  let response = WsHandshake.handshakeResponse("s3pPLMBiTxaQ9kYGzzhZRbK+xOo=");
  Test.assertion("response starts with 'HTTP/1.1 101'", "=", (a, b) => a === b, Js_string.substring(0, 12, response), "HTTP/1.1 101");
});

Test.test("WsHandshake.handshakeResponse includes Sec-WebSocket-Accept", () => {
  let accept = "s3pPLMBiTxaQ9kYGzzhZRbK+xOo=";
  let response = WsHandshake.handshakeResponse(accept);
  Test.assertion("response contains the accept header value", "=", (a, b) => a === b, response.includes("Sec-WebSocket-Accept: " + accept), true);
});

/*  Not a pure module */
