// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Node/Http.res.js";
import * as Buffer from "../Node/Buffer.res.js";
import * as Events from "../Node/Events.res.js";

let clients = {
  contents: []
};

function clientExists(socket) {
  let i = 0;
  let found = false;
  while (i < clients.contents.length) {
    let c = clients.contents[i];
    if (c !== undefined && c.socket === socket) {
      found = true;
      i = clients.contents.length;
    } else {
      i = i + 1 | 0;
    }
  };
  return found;
}

function removeFromClients(socket) {
  let cs = clients.contents;
  let len = cs.length;
  let i = 0;
  let found;
  while (i < len) {
    let c = cs[i];
    if (c !== undefined && c.socket === socket) {
      found = c;
      let head = cs.slice(0, i);
      let tail = cs.slice(i + 1 | 0, len - i | 0);
      clients.contents = head.concat(tail);
      i = len;
    } else {
      i = i + 1 | 0;
    }
  };
  return found;
}

function makeReloadFrame() {
  let payload = Buffer.fromString("reload", "utf8");
  let header = Buffer.fromArray([
    129,
    6
  ]);
  return Buffer.concat([
    header,
    payload
  ]);
}

function unregister(socket) {
  let maybe = removeFromClients(socket);
  if (maybe !== undefined) {
    Events.remove(socket, "close", maybe.onClose);
    Events.remove(socket, "error", maybe.onError);
    return;
  }
}

function register(socket) {
  if (clientExists(socket)) {
    return;
  }
  let onClose = () => unregister(socket);
  let onError = () => unregister(socket);
  Events.on(socket, "close", onClose);
  Events.on(socket, "error", onError);
  let entry = {
    socket: socket,
    onClose: onClose,
    onError: onError
  };
  clients.contents = clients.contents.concat([entry]);
}

function notifyReload() {
  let snapshot = clients.contents;
  if (snapshot.length === 0) {
    return;
  }
  let frame = makeReloadFrame();
  let i = 0;
  while (i < snapshot.length) {
    let entryOpt = snapshot[i];
    if (entryOpt !== undefined) {
      let errorListener = () => unregister(entryOpt.socket);
      Events.on(entryOpt.socket, "error", errorListener);
      try {
        Http.socketWriteBuffer(entryOpt.socket, frame);
      } catch (exn) {
        Events.remove(entryOpt.socket, "error", errorListener);
        unregister(entryOpt.socket);
      }
      i = i + 1 | 0;
    } else {
      i = i + 1 | 0;
    }
  };
}

export {
  register,
  unregister,
  notifyReload,
}
/* Http Not a pure module */
