// Generated by ReScript, PLEASE EDIT WITH CARE


function onAbort(sig, cb) {
  sig.onabort = cb;
}

function make(prim) {
  return new AbortController();
}

function signal(prim) {
  return prim.signal;
}

function abort(prim) {
  prim.abort();
}

export {
  make,
  signal,
  abort,
  onAbort,
}
/* No side effect */
