// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BufferImplMjs from "./BufferImpl.mjs";

function fromString(prim0, prim1) {
  return BufferImplMjs.fromString(prim0, prim1);
}

function fromArray(prim) {
  return BufferImplMjs.fromArray(prim);
}

function concat(prim) {
  return BufferImplMjs.concat(prim);
}

function length(prim) {
  return prim.length;
}

function readUInt8(prim0, prim1) {
  return prim0.readUInt8(prim1);
}

export {
  fromString,
  fromArray,
  concat,
  length,
  readUInt8,
}
/* ./BufferImpl.mjs Not a pure module */
