// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodecrypto from "node:crypto";

function sha1Base64(input) {
  let h = Nodecrypto.createHash("sha1");
  h.update(input);
  return h.digest("base64");
}

export {
  sha1Base64,
}
/* node:crypto Not a pure module */
