// Generated by ReScript, PLEASE EDIT WITH CARE


function on(prim0, prim1, prim2) {
  return prim0.on(prim1, prim2);
}

function remove(prim0, prim1, prim2) {
  return prim0.removeListener(prim1, prim2);
}

export {
  on,
  remove,
}
/* No side effect */
