// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Promises from "node:fs/promises";

function readdir(path) {
  return Promises.readdir(path, {
    withFileTypes: true
  });
}

function readTextFile(path) {
  return Promises.readFile(path, "utf-8");
}

function statIsFile(prim) {
  return prim.isFile();
}

function statIsDirectory(prim) {
  return prim.isDirectory();
}

function statIsSymlink(prim) {
  return prim.isSymbolicLink();
}

function statSize(prim) {
  return prim.size;
}

function direntName(prim) {
  return prim.name;
}

function direntIsDirectory(prim) {
  return prim.isDirectory();
}

function createReadStream(prim) {
  return Nodefs.createReadStream(prim);
}

function pipeStream(prim0, prim1) {
  return prim0.pipe(prim1);
}

function readFileSync(prim0, prim1) {
  return Nodefs.readFileSync(prim0, prim1);
}

function lstatSync(prim) {
  return Nodefs.lstatSync(prim);
}

function statSync(prim) {
  return Nodefs.statSync(prim);
}

function readdirSync(prim) {
  return Nodefs.readdirSync(prim);
}

function mkdirSync(prim) {
  Nodefs.mkdirSync(prim);
}

function rmdirSync(prim) {
  Nodefs.rmdirSync(prim);
}

function symlinkSync(prim0, prim1) {
  Nodefs.symlinkSync(prim0, prim1);
}

function unlinkSync(prim) {
  Nodefs.unlinkSync(prim);
}

function writeFileSync(prim0, prim1) {
  Nodefs.writeFileSync(prim0, prim1);
}

function lstat(prim) {
  return Promises.lstat(prim);
}

function stat(prim) {
  return Promises.stat(prim);
}

export {
  statIsFile,
  statIsDirectory,
  statIsSymlink,
  statSize,
  direntName,
  direntIsDirectory,
  createReadStream,
  pipeStream,
  readFileSync,
  lstatSync,
  statSync,
  readdirSync,
  mkdirSync,
  rmdirSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
  readdir,
  lstat,
  stat,
  readTextFile,
}
/* node:fs Not a pure module */
