// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";

function startWatcher(path, options, onEvent) {
  let wrappedCallback = (eventType, filename) => {
    let tmp;
    switch (eventType) {
      case "change" :
      case "rename" :
        tmp = {
          TAG: "Modified",
          _0: filename
        };
        break;
      default:
        tmp = "Other";
    }
    onEvent(tmp);
  };
  return Nodefs.watch(path, options, wrappedCallback);
}

export {
  startWatcher,
}
/* node:fs Not a pure module */
