// Generated by ReScript, PLEASE EDIT WITH CARE

function startWatcher(path, options, onEvent) {
  let wrappedCallback = (eventType, filename) => {
    let tmp;
    switch (eventType) {
      case "change":
      case "rename":
        tmp = {
          TAG: "Modified",
          _0: filename,
        };
        break;
      default:
        tmp = "Other";
    }
    onEvent(tmp);
  };
  return fs.watch(path, options, wrappedCallback);
}

function close(prim) {
  prim.close();
}

export { close, startWatcher };
/* No side effect */
