// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "./Fs.res.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Nodehttp from "node:http";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function socketWriteBuffer(socket, buf) {
  return new Promise((resolve, _reject) => {
    let settled = {
      contents: false
    };
    let mark = fn => {
      if (!settled.contents) {
        settled.contents = true;
        return fn();
      }
    };
    try {
      socket.write(buf, err => mark(() => {
        if (err == null) {
          return resolve({
            TAG: "Ok",
            _0: undefined
          });
        } else {
          return resolve({
            TAG: "Error",
            _0: err
          });
        }
      }));
      return;
    } catch (exn) {
      return mark(() => resolve({
        TAG: "Ok",
        _0: undefined
      }));
    }
  });
}

function buildRequest(req) {
  let method = req.method;
  let url = req.url;
  let rawHeaders = req.headers;
  let keys = Object.keys(rawHeaders);
  let headers = Stdlib_Array.make(keys.length, [
    "",
    ""
  ]);
  let i = 0;
  while (i < keys.length) {
    let k = Stdlib_Option.getOr(keys[i], "").toLowerCase();
    let v = Stdlib_Option.getOr(rawHeaders[k], "");
    headers[i] = [
      k,
      v
    ];
    i = i + 1 | 0;
  };
  let path = Stdlib_Option.getOr(Js_string.split("?", url)[0], url);
  return {
    method: method,
    path: path,
    headers: headers,
    clientIp: "127.0.0.1"
  };
}

function writeResponse(response, res) {
  return new Promise((resolve, _reject) => {
    let i = 0;
    while (i < response.headers.length) {
      let match = response.headers[i];
      if (match !== undefined) {
        res.setHeader(match[0], match[1]);
      }
      i = i + 1 | 0;
    };
    res.writeHead(response.status);
    let path = response.body;
    if (typeof path !== "object") {
      res.end(null);
    } else if (path.TAG === "File") {
      Fs.createReadStream(path._0).pipe(res);
    } else {
      res.end(path._0);
    }
    resolve();
  });
}

function closeServer(s) {
  return new Promise((resolve, _reject) => {
    s.close(_err => resolve());
  });
}

function startServer(port, hostname, handler, onWsUpgrade, signal) {
  let server = Nodehttp.createServer(async (req, res) => {
    let request = buildRequest(req);
    let outcome;
    try {
      outcome = await handler(request);
    } catch (exn) {
      outcome = {
        TAG: "Respond",
        _0: {
          status: 500,
          headers: [[
              "content-type",
              "text/plain; charset=utf-8"
            ]],
          body: "Empty"
        }
      };
    }
    if (typeof outcome !== "object") {
      return;
    }
    await writeResponse(outcome._0, res);
  });
  server.on("upgrade", async (req, socket, head) => {
    let request = buildRequest(req);
    let outcome;
    try {
      outcome = await handler(request);
    } catch (exn) {
      outcome = {
        TAG: "Respond",
        _0: {
          status: 500,
          headers: [[
              "content-type",
              "text/plain; charset=utf-8"
            ]],
          body: "Empty"
        }
      };
    }
    if (typeof outcome !== "object") {
      await onWsUpgrade(request, socket, head);
      return;
    }
    socket.destroy();
  });
  let closedResolve = {
    contents: undefined
  };
  let closed = new Promise((resolve, _reject) => {
    closedResolve.contents = resolve;
  });
  signal.onabort = () => {
    closeServer(server).then(() => {
      let r = closedResolve.contents;
      if (r !== undefined) {
        r();
      }
      return Promise.resolve();
    });
  };
  new Promise((resolve, _reject) => {
    server.listen(port, hostname, () => resolve());
  });
  return {
    server: server,
    closed: closed
  };
}

function socketWrite(prim0, prim1) {
  prim0.write(prim1);
}

export {
  socketWrite,
  socketWriteBuffer,
  closeServer,
  startServer,
}
/* Fs Not a pure module */
