// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodepath from "node:path";

function resolve(prim0, prim1) {
  return Nodepath.resolve(prim0, prim1);
}

function join(prim0, prim1) {
  return Nodepath.join(prim0, prim1);
}

function normalize(prim) {
  return Nodepath.normalize(prim);
}

function relative(prim0, prim1) {
  return Nodepath.relative(prim0, prim1);
}

function extname(prim) {
  return Nodepath.extname(prim);
}

function basename(prim) {
  return Nodepath.basename(prim);
}

export {
  resolve,
  join,
  normalize,
  relative,
  extname,
  basename,
}
/* node:path Not a pure module */
