// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodechild_process from "node:child_process";

function onChildExit(child, callback) {
  child.on("exit", (code, signal) => callback((code == null) ? undefined : Primitive_option.some(code), (signal == null) ? undefined : Primitive_option.some(signal)));
}

function onError(child, callback) {
  child.on("error", e => {
    if (!(e == null)) {
      return callback(e);
    }
  });
}

function exit(prim) {
  process.exit(prim);
}

let argv = process.argv;

function cwd(prim) {
  return process.cwd();
}

let execPath = process.execPath;

function spawn(prim0, prim1, prim2) {
  return Nodechild_process.spawn(prim0, prim1, prim2);
}

export {
  exit,
  argv,
  cwd,
  execPath,
  spawn,
  onChildExit,
  onError,
}
/* argv Not a pure module */
