// Generated by ReScript, PLEASE EDIT WITH CARE


function exit(prim) {
  process.exit(prim);
}

let argv = process.argv;

function cwd(prim) {
  return process.cwd();
}

export {
  exit,
  argv,
  cwd,
}
/* argv Not a pure module */
