// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "./Process.res.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let spawn = {
  contents: Process.spawn
};

function callSpawn(execPath, args, opts) {
  try {
    return {
      TAG: "Ok",
      _0: spawn.contents(execPath, args, opts)
    };
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    let m = Stdlib_JsExn.message(e);
    let msg = m !== undefined ? m : "unknown spawn error";
    return {
      TAG: "Error",
      _0: msg
    };
  }
}

export {
  spawn,
  callSpawn,
}
/* Process Not a pure module */
