// Generated by ReScript, PLEASE EDIT WITH CARE


function setTimeout(prim0, prim1) {
  return globalThis.setTimeout(prim0, prim1);
}

function clearTimeout(prim) {
  globalThis.clearTimeout(prim);
}

export {
  setTimeout,
  clearTimeout,
}
/* No side effect */
